#**BNCA Ledger Extraction using Python and the Data Visualization using PowerBI**

Total files for extraction are: 10

* CollegeLedger_B.Arch_2019_Pattern18_October2021.PDF
* SupplementaryCollegeLedger_B.Arch_2019_Pattern18_October2022_May4.PDF
* SupplementaryCollegeLedger_B.Arch_2019_Pattern18_October2022_March8.PDF
* CollegeLedger_B.Arch_2019_Pattern18_April2023.PDF
* CollegeLedger_B.Arch_2019_Pattern18_April2022.PDF



**---Project By MKSSS's AIT**

#**Project workflow to refer------>**
* First and root dataframe **P19_YearWise_Student_Info_df2123**

* Second Grdes dataframe **Pattern18_YearWise_Student_Info_df2123 --->** **Pattern18_Ledgers_Grades_Info_df0**

* Third and Final Grades dataframe is  **Pattern18_Ledgers_Grades_Info_df0 ---->** **Pattern18_YearWise_Grades_df2123**

* Fourth and for only SGPA records **Pattern18_YearWise_Student_Info_df2123 ---->** **SGPA_df27** [Only SGPA Recprds are here]

* Fifth and final SGPA With Year Result Dataframe - **Pattern18_YearWise_Student_Info_df2123 ---->** **SGPA_YearResult_df284** With a few validations

* Sixth and Final SGPA With Year Result Dataframe - **Pattern18_YearWise_Student_Info_df2123 ---->** **SGPA_YearResult_df285** With validations

###**Package Installation and Data Connectivity:**

In [ ]:
!pip install pdfplumber -q

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.0/49.0 kB 1.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 5.6/5.6 MB 15.0 MB/s eta 0:00:00
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 29.5 MB/s eta 0:00:00

In [ ]:
!pip install PyPDF2

Collecting PyPDF2
  Downloading pypdf2-3.0.1-py3-none-any.whl (232 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 232.6/232.6 kB 6.1 MB/s eta 0:00:00
Installing collected packages: PyPDF2
Successfully installed PyPDF2-3.0.1

In [ ]:
!pip install ghostscript
!pip install camelot-py[cv]
!pip install excalibur-py
!apt install ghostscript python3-tk

Collecting ghostscript
  Downloading ghostscript-0.7-py2.py3-none-any.whl (25 kB)
Requirement already satisfied: setuptools>=38.6.0 in /usr/local/lib/python3.10/dist-packages (from ghostscript) (67.7.2)
Installing collected packages: ghostscript
Successfully installed ghostscript-0.7
Collecting camelot-py[cv]
  Downloading camelot_py-0.11.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 928.1 kB/s eta 0:00:00
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (5.2.0)
Requirement already satisfied: click>=6.7 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (8.1.7)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (1.23.5)
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (3.1.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (1.5.3)
Requirement already satisfied: pdfminer.six>=20200726 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (20221105)
Collecting pypdf>=3.0.0 (from camelot-py[cv])
  Downloading pypdf-4.0.0-py3-none-any.whl (283 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 283.9/283.9 kB 5.9 MB/s eta 0:00:00
Requirement already satisfied: tabulate>=0.8.9 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (0.9.0)
Requirement already satisfied: ghostscript>=0.7 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (0.7)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (4.8.0.76)
INFO: pip is looking at multiple versions of camelot-py[cv] to determine which version is compatible with other requirements. This could take a while.
Collecting camelot-py[cv]
  Downloading camelot_py-0.10.1-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 1.6 MB/s eta 0:00:00
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]) (3.0.1)
  Downloading camelot_py-0.10.0-py3-none-any.whl (40 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 41.0/41.0 kB 4.0 MB/s eta 0:00:00
  Downloading camelot_py-0.9.0-py3-none-any.whl (43 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 43.2/43.2 kB 4.8 MB/s eta 0:00:00
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]) (1.1.0)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->camelot-py[cv]) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->camelot-py[cv]) (2023.3.post1)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]) (42.0.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (1.16.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas>=0.23.4->camelot-py[cv]) (1.16.0)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]) (2.21)
Installing collected packages: camelot-py
Successfully installed camelot-py-0.9.0
Collecting excalibur-py
  Downloading excalibur_py-0.4.3-py3-none-any.whl (1.5 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 1.5/1.5 MB 14.8 MB/s eta 0:00:00
Requirement already satisfied: camelot-py[cv]>=0.7.1 in /usr/local/lib/python3.10/dist-packages (from excalibur-py) (0.9.0)
Collecting celery>=4.1.1 (from excalibur-py)
  Downloading celery-5.3.6-py3-none-any.whl (422 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 422.0/422.0 kB 16.9 MB/s eta 0:00:00
Requirement already satisfied: Click>=7.0 in /usr/local/lib/python3.10/dist-packages (from excalibur-py) (8.1.7)
Collecting configparser<3.6.0,>=3.5.0 (from excalibur-py)
  Downloading configparser-3.5.3-py3-none-any.whl (21 kB)
Requirement already satisfied: Flask>=1.0.2 in /usr/local/lib/python3.10/dist-packages (from excalibur-py) (2.2.5)
Requirement already satisfied: SQLAlchemy>=1.2.12 in /usr/local/lib/python3.10/dist-packages (from excalibur-py) (2.0.24)
Collecting Werkzeug<1.0.0 (from excalibur-py)
  Downloading Werkzeug-0.16.1-py2.py3-none-any.whl (327 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 327.4/327.4 kB 18.7 MB/s eta 0:00:00
Requirement already satisfied: chardet>=3.0.4 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (5.2.0)
Requirement already satisfied: numpy>=1.13.3 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (1.23.5)
Requirement already satisfied: openpyxl>=2.5.8 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (3.1.2)
Requirement already satisfied: pandas>=0.23.4 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (1.5.3)
Requirement already satisfied: pdfminer.six>=20200726 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (20221105)
Requirement already satisfied: PyPDF2>=1.26.0 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (3.0.1)
Requirement already satisfied: opencv-python>=3.4.2.17 in /usr/local/lib/python3.10/dist-packages (from camelot-py[cv]>=0.7.1->excalibur-py) (4.8.0.76)
Collecting billiard<5.0,>=4.2.0 (from celery>=4.1.1->excalibur-py)
  Downloading billiard-4.2.0-py3-none-any.whl (86 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 86.7/86.7 kB 11.6 MB/s eta 0:00:00
Collecting click-didyoumean>=0.3.0 (from celery>=4.1.1->excalibur-py)
  Downloading click_didyoumean-0.3.0-py3-none-any.whl (2.7 kB)
Requirement already satisfied: click-plugins>=1.1.1 in /usr/local/lib/python3.10/dist-packages (from celery>=4.1.1->excalibur-py) (1.1.1)
Collecting click-repl>=0.2.0 (from celery>=4.1.1->excalibur-py)
  Downloading click_repl-0.3.0-py3-none-any.whl (10 kB)
Collecting kombu<6.0,>=5.3.4 (from celery>=4.1.1->excalibur-py)
  Downloading kombu-5.3.5-py3-none-any.whl (200 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 200.0/200.0 kB 21.7 MB/s eta 0:00:00
Requirement already satisfied: python-dateutil>=2.8.2 in /usr/local/lib/python3.10/dist-packages (from celery>=4.1.1->excalibur-py) (2.8.2)
Collecting tzdata>=2022.7 (from celery>=4.1.1->excalibur-py)
  Downloading tzdata-2023.4-py2.py3-none-any.whl (346 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 346.6/346.6 kB 17.4 MB/s eta 0:00:00
Collecting vine<6.0,>=5.1.0 (from celery>=4.1.1->excalibur-py)
  Downloading vine-5.1.0-py3-none-any.whl (9.6 kB)
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
Collecting Flask>=1.0.2 (from excalibur-py)
  Downloading flask-3.0.1-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.2/101.2 kB 13.5 MB/s eta 0:00:00
  Downloading flask-3.0.0-py3-none-any.whl (99 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 99.7/99.7 kB 12.0 MB/s eta 0:00:00
  Downloading flask-2.3.3-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.1/96.1 kB 11.8 MB/s eta 0:00:00
  Downloading Flask-2.3.2-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 96.9/96.9 kB 15.4 MB/s eta 0:00:00
  Downloading Flask-2.3.1-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.0/97.0 kB 14.0 MB/s eta 0:00:00
  Downloading Flask-2.3.0-py3-none-any.whl (96 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 97.0/97.0 kB 12.7 MB/s eta 0:00:00
  Downloading Flask-2.2.4-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.7/101.7 kB 15.3 MB/s eta 0:00:00
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
  Downloading Flask-2.2.3-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.8/101.8 kB 14.7 MB/s eta 0:00:00
  Downloading Flask-2.2.2-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.5/101.5 kB 15.3 MB/s eta 0:00:00
  Downloading Flask-2.2.1-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.5/101.5 kB 15.6 MB/s eta 0:00:00
  Downloading Flask-2.2.0-py3-none-any.whl (101 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 101.1/101.1 kB 13.2 MB/s eta 0:00:00
  Downloading Flask-2.1.3-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 13.8 MB/s eta 0:00:00
INFO: This is taking longer than usual. You might need to provide the dependency resolver with stricter constraints to reduce runtime. See https://pip.pypa.io/warnings/backtracking for guidance. If you want to abort this run, press Ctrl + C.
  Downloading Flask-2.1.2-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 12.5 MB/s eta 0:00:00
  Downloading Flask-2.1.1-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 12.1 MB/s eta 0:00:00
  Downloading Flask-2.1.0-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 14.9 MB/s eta 0:00:00
  Downloading Flask-2.0.3-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.6/95.6 kB 15.2 MB/s eta 0:00:00
  Downloading Flask-2.0.2-py3-none-any.whl (95 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 95.2/95.2 kB 13.6 MB/s eta 0:00:00
  Downloading Flask-2.0.1-py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.8/94.8 kB 12.8 MB/s eta 0:00:00
  Downloading Flask-2.0.0-py3-none-any.whl (93 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 93.2/93.2 kB 13.0 MB/s eta 0:00:00
  Downloading Flask-1.1.4-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 13.3 MB/s eta 0:00:00
Collecting Jinja2<3.0,>=2.10.1 (from Flask>=1.0.2->excalibur-py)
  Downloading Jinja2-2.11.3-py2.py3-none-any.whl (125 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 125.7/125.7 kB 19.2 MB/s eta 0:00:00
Collecting itsdangerous<2.0,>=0.24 (from Flask>=1.0.2->excalibur-py)
  Downloading itsdangerous-1.1.0-py2.py3-none-any.whl (16 kB)
Collecting Flask>=1.0.2 (from excalibur-py)
  Downloading Flask-1.1.3-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 14.2 MB/s eta 0:00:00
  Downloading Flask-1.1.2-py2.py3-none-any.whl (94 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 94.6/94.6 kB 14.4 MB/s eta 0:00:00
Requirement already satisfied: Jinja2>=2.10.1 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.0.2->excalibur-py) (3.1.3)
Requirement already satisfied: itsdangerous>=0.24 in /usr/local/lib/python3.10/dist-packages (from Flask>=1.0.2->excalibur-py) (2.1.2)
Requirement already satisfied: typing-extensions>=4.2.0 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy>=1.2.12->excalibur-py) (4.5.0)
Requirement already satisfied: greenlet!=0.4.17 in /usr/local/lib/python3.10/dist-packages (from SQLAlchemy>=1.2.12->excalibur-py) (3.0.3)
Requirement already satisfied: prompt-toolkit>=3.0.36 in /usr/local/lib/python3.10/dist-packages (from click-repl>=0.2.0->celery>=4.1.1->excalibur-py) (3.0.43)
Requirement already satisfied: MarkupSafe>=2.0 in /usr/local/lib/python3.10/dist-packages (from Jinja2>=2.10.1->Flask>=1.0.2->excalibur-py) (2.1.4)
Collecting amqp<6.0.0,>=5.1.1 (from kombu<6.0,>=5.3.4->celery>=4.1.1->excalibur-py)
  Downloading amqp-5.2.0-py3-none-any.whl (50 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 50.9/50.9 kB 7.4 MB/s eta 0:00:00
Requirement already satisfied: et-xmlfile in /usr/local/lib/python3.10/dist-packages (from openpyxl>=2.5.8->camelot-py[cv]>=0.7.1->excalibur-py) (1.1.0)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas>=0.23.4->camelot-py[cv]>=0.7.1->excalibur-py) (2023.3.post1)
Requirement already satisfied: charset-normalizer>=2.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py) (3.3.2)
Requirement already satisfied: cryptography>=36.0.0 in /usr/local/lib/python3.10/dist-packages (from pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py) (42.0.0)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.2->celery>=4.1.1->excalibur-py) (1.16.0)
Requirement already satisfied: cffi>=1.12 in /usr/local/lib/python3.10/dist-packages (from cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py) (1.16.0)
Requirement already satisfied: wcwidth in /usr/local/lib/python3.10/dist-packages (from prompt-toolkit>=3.0.36->click-repl>=0.2.0->celery>=4.1.1->excalibur-py) (0.2.13)
Requirement already satisfied: pycparser in /usr/local/lib/python3.10/dist-packages (from cffi>=1.12->cryptography>=36.0.0->pdfminer.six>=20200726->camelot-py[cv]>=0.7.1->excalibur-py) (2.21)
Installing collected packages: Werkzeug, vine, tzdata, configparser, click-didyoumean, billiard, Flask, click-repl, amqp, kombu, celery, excalibur-py
  Attempting uninstall: Werkzeug
    Found existing installation: Werkzeug 3.0.1
    Uninstalling Werkzeug-3.0.1:
      Successfully uninstalled Werkzeug-3.0.1
  Attempting uninstall: Flask
    Found existing installation: Flask 2.2.5
    Uninstalling Flask-2.2.5:
      Successfully uninstalled Flask-2.2.5
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorboard 2.15.1 requires werkzeug>=1.0.1, but you have werkzeug 0.16.1 which is incompatible.
Successfully installed Flask-1.1.2 Werkzeug-0.16.1 amqp-5.2.0 billiard-4.2.0 celery-5.3.6 click-didyoumean-0.3.0 click-repl-0.3.0 configparser-3.5.3 excalibur-py-0.4.3 kombu-5.3.5 tzdata-2023.4 vine-5.1.0
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
python3-tk is already the newest version (3.10.8-1~22.04).
The following additional packages will be installed:
  fonts-droid-fallback fonts-noto-mono fonts-urw-base35 libgs9 libgs9-common libidn12 libijs-0.35
  libjbig2dec0 poppler-data
Suggested packages:
  fonts-noto fonts-freefont-otf | fonts-freefont-ttf fonts-texgyre ghostscript-x poppler-utils
  fonts-japanese-mincho | fonts-ipafont-mincho fonts-japanese-gothic | fonts-ipafont-gothic
  fonts-arphic-ukai fonts-arphic-uming fonts-nanum
The following NEW packages will be installed:
  fonts-droid-fallback fonts-noto-mono fonts-urw-base35 ghostscript libgs9 libgs9-common libidn12
  libijs-0.35 libjbig2dec0 poppler-data
0 upgraded, 10 newly installed, 0 to remove and 31 not upgraded.
Need to get 16.7 MB of archives.
After this operation, 63.0 MB of additional disk space will be used.
Get:1 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-droid-fallback all 1:6.0.1r16-1.1build1 [1,805 kB]
Get:2 http://archive.ubuntu.com/ubuntu jammy/main amd64 poppler-data all 0.4.11-1 [2,171 kB]
Get:3 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-noto-mono all 20201225-1build1 [397 kB]
Get:4 http://archive.ubuntu.com/ubuntu jammy/main amd64 fonts-urw-base35 all 20200910-1 [6,367 kB]
Get:5 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9-common all 9.55.0~dfsg1-0ubuntu5.6 [751 kB]
Get:6 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libidn12 amd64 1.38-4ubuntu1 [60.0 kB]
Get:7 http://archive.ubuntu.com/ubuntu jammy/main amd64 libijs-0.35 amd64 0.35-15build2 [16.5 kB]
Get:8 http://archive.ubuntu.com/ubuntu jammy/main amd64 libjbig2dec0 amd64 0.19-3build2 [64.7 kB]
Get:9 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 libgs9 amd64 9.55.0~dfsg1-0ubuntu5.6 [5,031 kB]
Get:10 http://archive.ubuntu.com/ubuntu jammy-updates/main amd64 ghostscript amd64 9.55.0~dfsg1-0ubuntu5.6 [49.4 kB]
Fetched 16.7 MB in 2s (7,506 kB/s)
Selecting previously unselected package fonts-droid-fallback.
(Reading database ... 121671 files and directories currently installed.)
Preparing to unpack .../0-fonts-droid-fallback_1%3a6.0.1r16-1.1build1_all.deb ...
Unpacking fonts-droid-fallback (1:6.0.1r16-1.1build1) ...
Selecting previously unselected package poppler-data.
Preparing to unpack .../1-poppler-data_0.4.11-1_all.deb ...
Unpacking poppler-data (0.4.11-1) ...
Selecting previously unselected package fonts-noto-mono.
Preparing to unpack .../2-fonts-noto-mono_20201225-1build1_all.deb ...
Unpacking fonts-noto-mono (20201225-1build1) ...
Selecting previously unselected package fonts-urw-base35.
Preparing to unpack .../3-fonts-urw-base35_20200910-1_all.deb ...
Unpacking fonts-urw-base35 (20200910-1) ...
Selecting previously unselected package libgs9-common.
Preparing to unpack .../4-libgs9-common_9.55.0~dfsg1-0ubuntu5.6_all.deb ...
Unpacking libgs9-common (9.55.0~dfsg1-0ubuntu5.6) ...
Selecting previously unselected package libidn12:amd64.
Preparing to unpack .../5-libidn12_1.38-4ubuntu1_amd64.deb ...
Unpacking libidn12:amd64 (1.38-4ubuntu1) ...
Selecting previously unselected package libijs-0.35:amd64.
Preparing to unpack .../6-libijs-0.35_0.35-15build2_amd64.deb ...
Unpacking libijs-0.35:amd64 (0.35-15build2) ...
Selecting previously unselected package libjbig2dec0:amd64.
Preparing to unpack .../7-libjbig2dec0_0.19-3build2_amd64.deb ...
Unpacking libjbig2dec0:amd64 (0.19-3build2) ...
Selecting previously unselected package libgs9:amd64.
Preparing to unpack .../8-libgs9_9.55.0~dfsg1-0ubuntu5.6_amd64.deb ...
Unpacking libgs9:amd64 (9.55.0~dfsg1-0ubuntu5.6) ...
Selecting previously unselected package ghostscript.
Preparing to unpack .../9-ghostscript_9.55.0~dfsg1-0ubuntu5.6_amd64.deb ...
Unpacking ghostscript (9.55.0~dfsg1-0ubuntu5.6) ...
Setting up fonts-noto-mono (20201225-1build1) ...
Setting up libijs-0.35:amd64 (0.35-15build2) ...
Setting up fonts-urw-base35 (20200910-1) ...
Setting up poppler-data (0.4.11-1) ...
Setting up libjbig2dec0:amd64 (0.19-3build2) ...
Setting up libidn12:amd64 (1.38-4ubuntu1) ...
Setting up fonts-droid-fallback (1:6.0.1r16-1.1build1) ...
Setting up libgs9-common (9.55.0~dfsg1-0ubuntu5.6) ...
Setting up libgs9:amd64 (9.55.0~dfsg1-0ubuntu5.6) ...
Setting up ghostscript (9.55.0~dfsg1-0ubuntu5.6) ...
Processing triggers for fontconfig (2.13.1-4.2ubuntu5) ...
Processing triggers for libc-bin (2.35-0ubuntu3.4) ...
/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_5.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind_2_0.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbb.so.12 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc_proxy.so.2 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbbind.so.3 is not a symbolic link

/sbin/ldconfig.real: /usr/local/lib/libtbbmalloc.so.2 is not a symbolic link

Processing triggers for man-db (2.10.2-1) ...

In [ ]:
!pip install 'PyPDF2<3.0'

Collecting PyPDF2<3.0
  Downloading pypdf2-2.12.1-py3-none-any.whl (222 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 222.8/222.8 kB 3.7 MB/s eta 0:00:00
Installing collected packages: PyPDF2
  Attempting uninstall: PyPDF2
    Found existing installation: PyPDF2 3.0.1
    Uninstalling PyPDF2-3.0.1:
      Successfully uninstalled PyPDF2-3.0.1
Successfully installed PyPDF2-2.12.1

In [ ]:
#importing libraries
import pandas as pd
import pdfplumber
from google.colab import drive
import os

import re

In [ ]:
#mounting drive
drive.mount('/content/gdrive')

Mounted at /content/gdrive

In [ ]:
os.chdir("//content/gdrive/MyDrive/BNCA Project August 2023/BNCA_Sample_Data_Files/New_Data_Files") #changing to the directory qith the reports
os.getcwd()

'/content/gdrive/MyDrive/BNCA Project August 2023/BNCA_Sample_Data_Files/New_Data_Files'

###**Printing Total Number of Files along with their Names:**

In [ ]:
result_files = os.listdir() #setting week_files as all the pdf's inside our directory
print(result_files) #printing the os.listdir()
print("Total Number of Documnets:",len(result_files))

['BNCA Data Given By Tejaswini Maam', 'Copy of CollegeLedger_B.Arch_2019 Pattern_April2022.PDF', 'BNCA Pattern16 Data Files', ' BNCA Pattern 18 Ledgers', 'All Files of 2019 Pattern ']
Total Number of Documnets: 5

###**Ledgers Checking and entier text extraction of April-2022, October-2022, & April-2023 Ledgers**

* First and root dataframe **All_P19_YearDateWise_Student_Info_df1923**

* Second Grdes dataframe **All_P19_YearDateWise_Student_Info_df1923 --->** **All_P19_YearDateWise_Grades1618_Info_df1923**

* Third and Final Grades dataframe is  **All_P19_YearDateWise_Grades1618_Info_df1923 ---->** **Pat19_YearDateWise_Grad16_18_Info_df1923**

* Fourth and for only SGPA records **All_P19_YearDateWise_Student_Info_df1923 ---->** **P19_YearDateWise_SGPA_Info_df1923** [Only SGPA Recprds are here]


* Fifth and final SGPA With Year Result Dataframe - **All_P19_YearDateWise_Student_Info_df1923 ---->** **P19_YearDateWise_SGPA_YearResult_Info_df1923** With validations

##**All 8 files of Pattern 2019 and both the Grades i.e. 16 and 18 extraction**

* Getting Root data frame of Student Info ---->  **All_P19_YearDateWise_Student_Info_df1923**

In [ ]:
import os
import re
import PyPDF2
import pandas as pd

def extract_text_and_dates(pdf_path):
    text_by_page = []
    release_dates = []
    course_pattern_years = []
    ledger_years = []
    with open(pdf_path, "rb") as pdf_file:
        pdf_reader = PyPDF2.PdfReader(pdf_file)
        current_course_pattern_year = None
        current_ledger_year = None
        for page in pdf_reader.pages:
            page_text = page.extract_text()

            # Updated release_date_pattern to capture both formats
            release_date_matches = re.findall(r'(?:(\d{1,2}/\w+/\d{4})|(\d{1,2}-\w+-\d{4}))', page_text)
            release_date = next((date for date in release_date_matches[0] if date), None)

            # Append the release_date to the list
            release_dates.append(release_date)

            course_pattern_match = re.search(r'B\.Arch \((\d{4} Pattern)\)', page_text)
            if course_pattern_match:
                current_course_pattern_year = course_pattern_match.group(1)
            course_pattern_years.append(current_course_pattern_year)

            ledger_year_match = re.search(r'(Supplementary|College) Ledger\(([^)]+)\)', page_text)
            if ledger_year_match:
                current_ledger_year = ledger_year_match.group(2)
            ledger_years.append(current_ledger_year)

            page_text = re.sub(r'Page \d+', '', page_text)
            text_by_page.append(page_text)

    return text_by_page, release_dates, course_pattern_years, ledger_years

def process_partitions(all_text, release_dates, course_pattern_years, ledger_years, dotted_line_pattern):
    all_partitions = re.split(dotted_line_pattern, all_text)
    current_page = 0
    student_data = []
    for partition in all_partitions:
        page_breaks = partition.count('\f')
        current_page += page_breaks
        partition = partition.replace('\f', '')

        student_pattern = r"PRN: (\d+).*?Seat no.: (\d+).*?NAME: (.*?)(?: Mother - (.*?))?\n"
        matches = re.finditer(student_pattern, partition, re.DOTALL)
        for match in matches:
            prn, seat, name, mother = match.groups()
            release_date = release_dates[current_page - page_breaks]
            course_pattern_year = course_pattern_years[current_page - page_breaks]
            ledger_year = ledger_years[current_page - page_breaks]

            student_info = {
                "PRN": str(prn),
                "Seat No": str(seat),
                "Name": str(name),
                "Mother Name": str(mother) if mother else None,
                "Course Pattern Year": course_pattern_year,
                "Ledger Year": ledger_year,
                "Ledger Release Date": release_date,
                "Student Info Lines": partition.strip().split('\n')
            }
            student_data.append(student_info)
    return student_data

pdf_directory = "/content/gdrive/MyDrive/BNCA Project August 2023/BNCA_Sample_Data_Files/New_Data_Files/All Files of 2019 Pattern "
pdf_files = [file for file in os.listdir(pdf_directory) if file.lower().endswith(".pdf")]

print("Total files for extraction are:", len(pdf_files))

all_student_records = []
dotted_line_pattern = r"\.{100,}"

for pdf_file_name in pdf_files:
    pdf_file_path = os.path.join(pdf_directory, pdf_file_name)
    pages_text, pages_release_dates, pages_course_pattern_years, pages_ledger_years = extract_text_and_dates(pdf_file_path)

    all_text = '\f'.join(pages_text)
    student_records = process_partitions(all_text, pages_release_dates, pages_course_pattern_years, pages_ledger_years, dotted_line_pattern)
    all_student_records.extend(student_records)
    print("Just cross-checking the files:", pdf_file_name)

All_P19_YearDateWise_Student_Info_df1923 = pd.DataFrame(all_student_records)
#print(All_P19_YearDateWise_Student_Info_df1923)

Total files for extraction are: 8
Just cross-checking the files: CollegeLedger_Pattern_2019_Grades18_April2021.pdf
Just cross-checking the files: CollegeLedger_B.Arch_Pattern_2019_Grades18_October2021.PDF
Just cross-checking the files: CollegeLedger_B.Arch_Pattern_2019_Grades18_April2023.PDF
Just cross-checking the files: CollegeLedger_B.Arch_Pattern_2019_Grades18_April2022.PDF
Just cross-checking the files: SupplementaryCollegeLedger_B.Arch_Pattern_2019_Grades18_October2022_March8.PDF
Just cross-checking the files: SupplementaryCollegeLedger_B.Arch_Pattern_2019_Grades18_October2022_May4.PDF
Just cross-checking the files: CollegerLedger_Pattern_2019_Grades16_April2020.PDF
Just cross-checking the files: CollegeLedger_Pattern_2019_Grades16_October2019.PDF

###Testing for **All_P19_YearDateWise_Student_Info_df1923**

In [ ]:
All_P19_YearDateWise_Student_Info_df1923

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
0,1151518001719,631,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
1,1151518002556,556,BHUTADA RIDDHI NISHANT,SARITA NISHANT BHUTADA,2019 Pattern,Apr-2021,28-Aug-2021,[........Savitribai Phule Pune University28-Au...
2,1151518002587,570,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Apr-2021,28-Aug-2021,[........Savitribai Phule Pune University28-Au...
3,1151518002600,751,RAJURKAR JUI AJAY,RAJURKAR RAJSHREE AJAY,2019 Pattern,Apr-2021,28-Aug-2021,[........Savitribai Phule Pune University28-Au...
4,1151919000946,828,THOMAS CELESTE HENRY,JYOTI,2019 Pattern,Apr-2021,28-Aug-2021,[........Savitribai Phule Pune University28-Au...
...,...,...,...,...,...,...,...,...
3012,1151919002599,476,SAKSHI SANJAY JANGAM,SUVARNA JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,[PRN: 1151919002599 Seat no.: 476 NAME: SA...
3013,1151919002605,460,PULLIWAR RIJUTA PRASAD,POOJA PULLIWAR,2019 Pattern,Oct-2019,25/Jan/2020,[PRN: 1151919002605 Seat no.: 460 NAME: PU...
3014,1151919002612,452,PATIL TEJAL RAJARAM,ALKA RAJARAM PATIL,2019 Pattern,Oct-2019,25/Jan/2020,[PRN: 1151919002612 Seat no.: 452 NAME: PA...
3015,1151919002629,437,NASHRAH RAHIM,ANJUM RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,"[Savitribai Phule Pune University, 25/Jan/2020..."
3016,1151919002636,459,PUJARI SAYALI DATTATRAY,PUJARI SUNITA DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,[PRN: 1151919002636 Seat no.: 459 NAME: PU...

In [ ]:
All_P19_YearDateWise_Student_Info_df1923['Student Info Lines'].iloc[2677]

['.......',
 'PRN: 1151922002982   Seat no.: 13969   NAME: RHEA RAHUL CHOUDHARI   Mother - SEJAL',
 'BASIC DESIGN',
 '1201901       ---    ---    ---    ---    ---    ---    ---  * 126    ---    ---    ---    ---    ---  126      10   D     6  60',
 'BUILDING CONSTRUCTION & MATERIALS I [P]',
 '1201902       ---    ---  * 021  * 048    ---    ---    ---    ---    ---    ---    ---    ---    ---  069       2   C     7  14',
 'BUILDING CONSTRUCTION & MATERIALS I [SV]',
 '1201903       ---    ---    ---    ---    ---    ---    ---    ---  * 075    ---    ---    ---    ---  075       5   B     8  40',
 'THEORY OF STRUCTURES I',
 '1201904       ---    ---  * 029  * 053    ---    ---    ---    ---    ---    ---    ---    ---    ---  082       2   A     9  18',
 'ARCHITECTURAL GRAPHICS AND DRAWING I',
 '1201905       ---    ---    ---    ---    ---    ---  * 062    ---    ---    ---    ---    ---    ---  062       3   C     7  21',
 'HISTORY OF ARCH & CULTURE I',
 '1201906       ---    ---    ---    ---    ---  * 035    ---    ---    ---    ---    ---    ---    ---  035       2   B     8  16',
 'COMMUNICATION SKILLS',
 '1201907       ---    ---    ---    ---    ---  * 043    ---    ---    ---    ---    ---    ---    ---  043       2   A     9  18',
 'WORKSHOP I',
 '1201908       ---    ---    ---    ---    ---    ---  * 060    ---    ---    ---    ---    ---    ---  060       2   C     7  14',
 'CRAFTS',
 '1201917A      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    --- *"AC"',
 '%^',
 '    First Semester SGPA : 7.179 Credits Earned/Total : 28/28',
 ' Total Credit Points: 201',
 'PHYSICAL EDUCATION',
 '9201917       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    --- *"A"',
 '%^',
 ' % Ancillary   ^ Non-Credit Course']

In [ ]:
All_P19_YearDateWise_Student_Info_df1923['Ledger Release Date'].unique()

array(['28-Aug-2021', '09-Apr-2022', '18-Sep-2023', '30-Aug-2022',
       '08-Mar-2023', '04-May-2023', '21-Jul-2020', '25/Jan/2020'],
      dtype=object)

In [ ]:
All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['Ledger Release Date']== None]

Empty DataFrame
Columns: [PRN, Seat No, Name, Mother Name, Course Pattern Year, Ledger Year, Ledger Release Date, Student Info Lines]
Index: []

In [ ]:
All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['Ledger Year']=='Oct-2021']

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
333,1151518001719,917,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Oct-2021,09-Apr-2022,"[Savitribai Phule Pune University, 09-Apr-2022..."
334,1151518002556,796,BHUTADA RIDDHI NISHANT,SARITA NISHANT BHUTADA,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
335,1151518002587,819,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
336,1151518002600,1090,RAJURKAR JUI AJAY,RAJURKAR RAJSHREE AJAY,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
337,1151730262,786,BHARATI AVANTIKA MAHENDRA,ROHINI,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
...,...,...,...,...,...,...,...,...
832,1151921002808,1109,RUTUJA MAHESH URNEY,SMITA MAHESH URNEY,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
833,1151921002815,934,KAWANE ANANYA SUDARSHAN,KAWANE GITANJALEE SUDARSHAN,2019 Pattern,Oct-2021,09-Apr-2022,"[......., PRN: 1151921002815 Seat no.: 934 ..."
834,1151921002822,916,JOSHI YADNYA GANESH,SIDDHI GANESH JOSHI,2019 Pattern,Oct-2021,09-Apr-2022,"[......., PRN: 1151921002822 Seat no.: 916 ..."
835,1151921002839,927,KANAK MANKAR,SWATI MANKAR,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
836,1151921002846,936,KEDARI SANKASHTI SHYAM,ARCHANA SHYAM KEDARI,2019 Pattern,Oct-2021,09-Apr-2022,"[......., PRN: 1151921002846 Seat no.: 936 ..."

In [ ]:
#1151921002846
All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['PRN']=='1151921002846']

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
836,1151921002846,936,KEDARI SANKASHTI SHYAM,ARCHANA SHYAM KEDARI,2019 Pattern,Oct-2021,09-Apr-2022,"[......., PRN: 1151921002846 Seat no.: 936 ..."
1332,1151921002846,11233,KEDARI SANKASHTI SHYAM,ARCHANA SHYAM KEDARI,2019 Pattern,Apr-2023,18-Sep-2023,"[.......Savitribai Phule Pune University, 18-S..."
2001,1151921002846,10915,KEDARI SANKASHTI SHYAM,ARCHANA SHYAM KEDARI,2019 Pattern,Apr-2022,30-Aug-2022,"[.......Savitribai Phule Pune University, 30-A..."
2430,1151921002846,10904,KEDARI SANKASHTI SHYAM,ARCHANA SHYAM KEDARI,2019 Pattern,Oct-2022,08-Mar-2023,"[......., PRN: 1151921002846 Seat no.: 10904..."

In [ ]:
#1151921002808
All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['PRN']=='1151921002808']

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
832,1151921002808,1109,RUTUJA MAHESH URNEY,SMITA MAHESH URNEY,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
1328,1151921002808,11461,RUTUJA MAHESH URNEY,SMITA MAHESH URNEY,2019 Pattern,Apr-2023,18-Sep-2023,"[.......Savitribai Phule Pune University, 18-S..."
1997,1151921002808,11089,RUTUJA MAHESH URNEY,SMITA MAHESH URNEY,2019 Pattern,Apr-2022,30-Aug-2022,"[.......Savitribai Phule Pune University, 30-A..."
2427,1151921002808,11079,RUTUJA MAHESH URNEY,SMITA MAHESH URNEY,2019 Pattern,Oct-2022,08-Mar-2023,"[.......Savitribai Phule Pune University, 08-M..."

In [ ]:
#All_P19_YearDateWise_Student_Info_df1923['Student Info Lines'][500]

In [ ]:
#All_P19_YearDateWise_Student_Info_df1923['Student Info Lines'][1]

In [ ]:
len(All_P19_YearDateWise_Student_Info_df1923['PRN'])

3017

In [ ]:
len(All_P19_YearDateWise_Student_Info_df1923['PRN'].unique())

693

In [ ]:
All_P19_YearDateWise_Student_Info_df1923['PRN'].value_counts().T

1151919001028    8
1151919002018    8
1151919001707    8
1151919001226    8
1151919001844    8
                ..
1151921002617    1
1151920002311    1
1151920002205    1
1151518001931    1
1151919002636    1
Name: PRN, Length: 693, dtype: int64

In [ ]:
max(All_P19_YearDateWise_Student_Info_df1923['PRN'].value_counts().T)

8

In [ ]:
#1151919001028

All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['PRN']=='1151919001028']

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
11,1151919001028,594,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
345,1151919001028,858,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
853,1151919001028,11138,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Apr-2023,18-Sep-2023,"[.......Savitribai Phule Pune University, 18-S..."
1513,1151919001028,10838,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Apr-2022,30-Aug-2022,"[.......Savitribai Phule Pune University, 30-A..."
2017,1151919001028,10831,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Oct-2022,08-Mar-2023,"[.......Savitribai Phule Pune University, 08-M..."
2432,1151919001028,10831,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Oct-2022,04-May-2023,"[.......Savitribai Phule Pune University, 04-M..."
2687,1151919001028,266,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Apr-2020,21-Jul-2020,[.......Savitribai Phule Pune University21-Jul...
2855,1151919001028,379,GADGIL NIKITA YOGESH,YAMINI,2019 Pattern,Oct-2019,25/Jan/2020,"[Savitribai Phule Pune University, 25/Jan/2020..."

In [ ]:
All_P19_YearDateWise_Student_Info_df1923.iloc[:20,:].tail()

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
15,1151919001066,706,NEVASE TANISHKA SUNIL,SHARMILA SUNIL NEVASE,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
16,1151919001073,559,BIRNALE ANUSHKA AJITKUMAR,NEELAM,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
17,1151919001080,825,THAKARE VIBHA KAILAS,KIRAN KAILAS THAKARE,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
18,1151919001097,691,MOREY PRADNYA PRAKASH,VIJAYA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
19,1151919001103,814,SURABHI VARMA,PARINA VARMA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...

In [ ]:
All_P19_YearDateWise_Student_Info_df1923.iloc[21:41,:].head()

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
21,1151919001127,611,HIRWANI MISHIKA VINOD,SAPNA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
22,1151919001134,608,GUNJAL JUILEE JITENDRA,GUNJAL ANJALI JITENDRA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
23,1151919001141,655,KOLTE SHREYA RAJARAM,KOLTE SHITAL RAJARAM,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
24,1151919001158,551,BHOJANE VAISHNAVI KAILASH,SANGITA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
25,1151919001165,604,GOJAMGUNDE NISHIGANDHA ABHIJEET,SUWARNMALA ABHIJEET GOJAMGUNDE,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...

###**Testing for two page records**

In [ ]:
temp_new_87=All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['PRN']=='1151518002587']
temp_new_87

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
2,1151518002587,570,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Apr-2021,28-Aug-2021,[........Savitribai Phule Pune University28-Au...
335,1151518002587,819,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Oct-2021,09-Apr-2022,"[.......Savitribai Phule Pune University, 09-A..."
842,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Apr-2023,18-Sep-2023,"[.......Savitribai Phule Pune University, 18-S..."
1503,1151518002587,10800,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Apr-2022,30-Aug-2022,"[.......Savitribai Phule Pune University, 30-A..."
2005,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Oct-2022,08-Mar-2023,"[.......Savitribai Phule Pune University, 08-M..."
2431,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,ANUSAYA,2019 Pattern,Oct-2022,04-May-2023,"[Savitribai Phule Pune University, 04-May-2023..."

In [ ]:
temp_new_87.iloc[2,-1]

['.......Savitribai Phule Pune University',
 '18-Sep-2023 Pune-411 007',
 'B.Arch (2019 Pattern)',
 'College Ledger(Apr-2023)',
 '              Int    Ext    Int    Ext    UEX    SS     SS     SS     SV     SV     SV     SV     SV   Tot     Crd   Grd Grd Crd',
 '       Min    000    000    000    032    045    025    050    125    050    075    125    150    275                    Pnt Pnt',
 '       Max    025    025    030    070    100    050    100    250    100    150    250    300    550',
 '           ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~  ~~~ ~~~ ~~~   ~~~ ~~~ ~~~CARP011040-DR.BHANUBEN NANAVATI COLLEGE OF ARCHITECTURE FOR WOMEN,PUNE',
 'PRN: 1151518002587   Seat no.: 11082   NAME: DAMSE YOGESHWARI DASHARATH   Mother - ANUSAYA',
 'ARCHITECTURAL DESIGN II',
 '2201917       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  P 145    ---    ---  145      10   D     6  60',
 'BUILDING CONSTRUCTION & MATERIALS III [P]',
 '2201918       ---    ---  P 021  P 034    ---    ---    ---    ---    ---    ---    ---    ---    ---  055       2   D     6  12',
 'BUILDING CONSTRUCTION & MATERIALS III [SV]',
 '2201919       ---    ---    ---    ---    ---    ---    ---    ---  P 050    ---    ---    ---    ---  050       5   D     6  30',
 'THEORY OF STRUCTURES III',
 '2201920       ---    ---  P 013  P 032    ---    ---    ---    ---    ---    ---    ---    ---    ---  045       2   E     5  10',
 'COMPUTER AIDED DRAWING AND GRAPHICS',
 '2201921       ---    ---    ---    ---    ---  P 028    ---    ---    ---    ---    ---    ---    ---  028       2   D     6  12',
 'HISTORY OF ARCH & CULTURE III',
 '2201922       ---    ---    ---    ---    ---  P 034    ---    ---    ---    ---    ---    ---    ---  034       2   C     7  14',
 'BUILDING SERVICES I [P]',
 '2201923       ---    ---  P 013  P 042    ---    ---    ---    ---    ---    ---    ---    ---    ---  055       2   D     6  12',
 'BUILDING SERVICES I [SS]',
 '2201924       ---    ---    ---    ---    ---  P 025    ---    ---    ---    ---    ---    ---    ---  025       1   D     6   6',
 'CLIMATOLOGY',
 '2201925       ---    ---    ---    ---    ---  P 033    ---    ---    ---    ---    ---    ---    ---  033       2   C     7  14',
 '    Third Semester SGPA : 6.071 Credits Earned/Total : 28/28',
 ' Total Credit Points: 170',
 'ARCHITECTURAL DESIGN III',
 '2201926       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  * 100    ---    ---  100 FFF  10   F     0   0',
 'BUILDING CONSTRUCTION & MATERIALS IV [P]',
 '2201927       ---    ---  P 014  P 042    ---    ---    ---    ---    ---    ---    ---    ---    ---  056       2   D     6  12',
 'BUILDING CONSTRUCTION & MATERIALS IV [SV]',
 '2201928       ---    ---    ---    ---    ---    ---    ---    ---  P 050    ---    ---    ---    ---  050       5   D     6  30',
 'THEORY OF STRUCTURES IV',
 '2201929       ---    ---  P 013  * 004    ---    ---    ---    ---    ---    ---    ---    ---    ---  017 FFF   2   F     0   0',
 'ENVIRONMENTAL SCIENCE',
 '2201930       ---    ---    ---    ---    ---  P 027    ---    ---    ---    ---    ---    ---    ---  027       2   D     6  12',
 'HISTORY OF ARCH & CULTURE IV',
 '2201931       ---    ---    ---    ---    ---  P 025    ---    ---    ---    ---    ---    ---    ---  025       2   D     6  12',
 'BUILDING SERVICES II [P]',
 '2201932       ---    ---  P 016  P 052    ---    ---    ---    ---    ---    ---    ---    ---    ---  068       2   C     7  14',
 'BUILDING SERVICES II [SS]',
 '2201933       ---    ---    ---    ---    ---  P 033    ---    ---    ---    ---    ---    ---    ---  033       1   C     7   7',
 'SITE SURVEY AND ANALYSIS',
 '2201934       ---    ---    ---    ---    ---  P 035    ---    ---    ---    ---    ---    ---    ---  035       2   B     8  16',
 'YOGA',
 '2201936F      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  "AC"',
 '%^',
 '    Fourth Semester SGPA : ----- Credits Earned/Total : 16/28',
 ' Total Credit Points: 103',
 'Second Year Result : Fail A.T.K.T.   Total Credits Earned : 44/56',
 'ARCHITECTURAL DESIGN IV',
 '3201935       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  * AAA    ---    ---  000 FFF  10   F     0   0',
 'BUILDING CONSTRUCTION & MATERIALS V [P]',
 '3201936       ---    ---  P 020  P 035    ---    ---    ---    ---    ---    ---    ---    ---    ---  055       2   D     6  12',
 'BUILDING CONSTRUCTION & MATERIALS V [SV]',
 '3201937       ---    ---    ---    ---    ---    ---    ---    ---  * AAA    ---    ---    ---    ---  000 FFF   4   F     0   0',
 'THEORY OF STRUCTURES V',
 '3201938       ---    ---  P 013  * 006    ---    ---    ---    ---    ---    ---    ---    ---    ---  019 FFF   2   F     0   0',
 'LANDSCAPE ARCHITECTURE',
 '3201939       ---    ---    ---    ---    ---    ---  P 050    ---    ---    ---    ---    ---    ---  050       3   D     6  18',
 'ELECTIVE I [CONTEMPORARY ARCHITECTURE]',
 '3201940       ---    ---    ---    ---    ---    ---  P 051    ---    ---    ---    ---    ---    ---  051       2   D     6  12',
 'BUILDING SERVICES III [P]',
 '3201941       ---    ---  P 023  P 043    ---    ---    ---    ---    ---    ---    ---    ---    ---  066       2   C     7  14',
 'BUILDING SERVICES III[SS]',
 '3201942       ---    ---    ---    ---    ---  P 030    ---    ---    ---    ---    ---    ---    ---  030       1   C     7   7',
 'WORKING DRAWING I',
 '3201943       ---    ---    ---    ---    ---    ---  * 040    ---    ---    ---    ---    ---    ---  040 FFF   2   F     0   0',
 'CULINARY ART AND PRACTICES',
 '3201953I      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  "AC"',
 '%^',
 '    Fifth Semester SGPA : ----- Credits Earned/Total : 10/28',
 ' Total Credit Points: 63',
 'ARCHITECTURAL DESIGN V[SV]',
 '3201944       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  * AAA    ---    ---  000 FFF   8   F     0   0',
 'ARCHITECTURAL DESIGN V*[P]',
 '3201945       ---    ---    ---    ---  P AAA    ---    ---    ---    ---    ---    ---    ---    ---  000 FFF   2   F     0   0',
 'BUILDING CONSTRUCTION & MATERIALS VI',
 '3201946       ---    ---    ---    ---    ---    ---    ---    ---    ---  * AAA    ---    ---    ---  000 FFF   6   F     0   0',
 'THEORY OF STRUCTURES VI',
 '3201947       ---    ---  P 018  * 001    ---    ---    ---    ---    ---    ---    ---    ---    ---  019 FFF   2   F     0   0',
 'RESEARCH IN ARCHITECTURE I',
 '3201948       ---    ---    ---    ---    ---  * 026    ---    ---    ---    ---    ---    ---    ---  026       2   D     6  12',
 'ELECTIVE II',
 '3201949       ---    ---    ---    ---    ---    ---  * AAA    ---    ---    ---    ---    ---    ---  000 FFF   3   F     0   0',
 'BUILDING SERVICES IV[P]Savitribai Phule Pune University',
 '18-Sep-2023 Pune-411 007',
 'B.Arch (2019 Pattern)',
 'College Ledger(Apr-2023)',
 '              Int    Ext    Int    Ext    UEX    SS     SS     SS     SV     SV     SV     SV     SV   Tot     Crd   Grd Grd Crd',
 '       Min    000    000    000    032    045    025    050    125    050    075    125    150    275                    Pnt Pnt',
 '       Max    025    025    030    070    100    050    100    250    100    150    250    300    550',
 '           ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~  ~~~ ~~~ ~~~   ~~~ ~~~ ~~~CARP011040-DR.BHANUBEN NANAVATI COLLEGE OF ARCHITECTURE FOR WOMEN,PUNE',
 'continued....',
 '3201950       ---    ---  P 017  * 014    ---    ---    ---    ---    ---    ---    ---    ---    ---  031 FFF   2   F     0   0',
 'BUILDING SERVICES IV[SS]',
 '3201951       ---    ---    ---    ---    ---  * 012    ---    ---    ---    ---    ---    ---    ---  012 FFF   1   F     0   0',
 'WORKING DRAWING II',
 '3201952       ---    ---    ---    ---    ---    ---  * 051    ---    ---    ---    ---    ---    ---  051       2   D     6  12',
 'BASICS OF ACCOUNTING AND BOOK KEEPING',
 '3201954G      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  "AC"',
 '%^',
 '    Sixth Semester SGPA : ----- Credits Earned/Total : 4/28',
 ' Total Credit Points: 24',
 'Third Year Result : Fail   Total Credits Earned : 14/56',
 'PHYSICAL EDUCATION',
 '9201917       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  "C"',
 '%^',
 ' % Ancillary   ^ Non-Credit Course']

In [ ]:
All_P19_YearDateWise_Student_Info_df1923.columns

Index(['PRN', 'Seat No', 'Name', 'Mother Name', 'Course Pattern Year',
       'Ledger Year', 'Ledger Release Date', 'Student Info Lines'],
      dtype='object')

###Testing for

In [ ]:
temp_a21_1719=All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['PRN']=='1151518001719']
temp_a21_1719

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
0,1151518001719,631,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Apr-2021,28-Aug-2021,[Savitribai Phule Pune University28-Aug-2021 P...
333,1151518001719,917,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Oct-2021,09-Apr-2022,"[Savitribai Phule Pune University, 09-Apr-2022..."
839,1151518001719,11210,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Apr-2023,18-Sep-2023,"[.......Savitribai Phule Pune University, 18-S..."
1501,1151518001719,10896,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Apr-2022,30-Aug-2022,"[Savitribai Phule Pune University, 30-Aug-2022..."
2003,1151518001719,10887,KABRA SAKSHI GOVIND,RADHA,2019 Pattern,Oct-2022,08-Mar-2023,"[.......Savitribai Phule Pune University, 08-M..."

In [ ]:
temp_a21_1719['Student Info Lines'].iloc[0]

['Savitribai Phule Pune University28-Aug-2021 Pune-411 007',
 'B.Arch (2019 Pattern)',
 'College Ledger(Apr-2021)',
 '              Int    Ext    Int    Ext    UEX    SS     SS     SS     SV     SV     SV     SV     SV   Tot     Crd   Grd Grd Crd',
 '       Min    000    000    000    032    045    025    050    125    050    075    125    150    275                    Pnt Pnt',
 '       Max    025    025    030    070    100    050    100    250    100    150    250    300    550',
 '           ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~  ~~~ ~~~ ~~~   ~~~ ~~~ ~~~CARP011040-DR.BHANUBEN NANAVATI COLLEGE OF ARCHITECTURE FOR WOMEN,PUNE',
 'PRN: 1151518001719   Seat no.: 631   NAME: KABRA SAKSHI GOVIND   Mother - RADHA',
 'BASIC DESIGN1201901       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'BUILDING CONSTRUCTION & MATERIALS I [P]1201902       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'BUILDING CONSTRUCTION & MATERIALS I [SV]1201903       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'THEORY OF STRUCTURES I1201904       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'ARCHITECTURAL GRAPHICS AND DRAWING I1201905       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'HISTORY OF ARCH & CULTURE I1201906       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'COMMUNICATION SKILLS1201907       ---    ---    ---    ---    ---  * 029    ---    ---    ---    ---    ---    ---    ---  029       2   D     612',
 'WORKSHOP I1201908       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'CRAFTS1201917A      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 'CREATIVE WRITING1201917B      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 'PERFORMING ARTS1201917C      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 '    First Semester SGPA : 6.000 Credits Earned/Total : 28/28 Total Credit Points: 12',
 'ARCHITECTURAL DESIGN I1201909       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'BUILDING CONSTRUCTION & MATERIALS II [P]1201910       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'BUILDING CONSTRUCTION & MATERIALS II [SV]1201911       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'THEORY OF STRUCTURES II1201912       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'ARCHITECTURAL GRAPHICS AND DRAWING II1201913       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'HISTORY OF ARCH & CULTURE II1201914       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'FUNDAMENTALS OF ARCHITECTURE1201915       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'WORKSHOP II1201916       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
 'CRAFTS1201918A      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 'CREATIVE WRITING1201918B      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 'PERFORMING ARTS1201918C      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
 '    Second Semester SGPA : 0.000 Credits Earned/Total : 28/28 Total Credit Points: 0',
 'First Year Total Credits Earned : 56/56',
 'ARCHITECTURAL DESIGN II2201917       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  P 135    ---    ---  135      10   D     660',
 'BUILDING CONSTRUCTION & MATERIALS III [P]2201918       ---    ---  P 023  P 050    ---    ---    ---    ---    ---    ---    ---    ---    ---  073       2   B     816',
 'BUILDING CONSTRUCTION & MATERIALS III [SV]2201919       ---    ---    ---    ---    ---    ---    ---    ---  P 058    ---    ---    ---    ---  058       5   D     630',
 'THEORY OF STRUCTURES III2201920       ---    ---  P 014  P 032    ---    ---    ---    ---    ---    ---    ---    ---    ---  046       2   E     510                                     #COMPUTER AIDED DRAWING AND GRAPHICS2201921       ---    ---    ---    ---    ---  P 028    ---    ---    ---    ---    ---    ---    ---  028       2   D     612',
 'HISTORY OF ARCH & CULTURE III2201922       ---    ---    ---    ---    ---  P 039    ---    ---    ---    ---    ---    ---    ---  039       2   B     816',
 'BUILDING SERVICES I [P]2201923       ---    ---  P 026  P 062    ---    ---    ---    ---    ---    ---    ---    ---    ---  088       2   A     918',
 'BUILDING SERVICES I [SS]2201924       ---    ---    ---    ---    ---  P 025    ---    ---    ---    ---    ---    ---    ---  025       1   D     66',
 'CLIMATOLOGY2201925       ---    ---    ---    ---    ---  P 035    ---    ---    ---    ---    ---    ---    ---  035       2   B     816',
 '    Third Semester SGPA : 6.571 Credits Earned/Total : 28/28Savitribai Phule Pune University28-Aug-2021 Pune-411 007',
 'B.Arch (2019 Pattern)',
 'College Ledger(Apr-2021)',
 '              Int    Ext    Int    Ext    UEX    SS     SS     SS     SV     SV     SV     SV     SV   Tot     Crd   Grd Grd Crd',
 '       Min    000    000    000    032    045    025    050    125    050    075    125    150    275                    Pnt Pnt',
 '       Max    025    025    030    070    100    050    100    250    100    150    250    300    550',
 '           ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~ ~~~~~~  ~~~ ~~~ ~~~   ~~~ ~~~ ~~~CARP011040-DR.BHANUBEN NANAVATI COLLEGE OF ARCHITECTURE FOR WOMEN,PUNE',
 'continued....',
 ' Total Credit Points: 184',
 'ARCHITECTURAL DESIGN III',
 '2201926       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  * 115    ---    ---  115 FFF  10   F     0',
 '0',
 'BUILDING CONSTRUCTION & MATERIALS IV [P]',
 '2201927       ---    ---  * 024  * 048    ---    ---    ---    ---    ---    ---    ---    ---    ---  072       2   B     8',
 '16',
 'BUILDING CONSTRUCTION & MATERIALS IV [SV]',
 '2201928       ---    ---    ---    ---    ---    ---    ---    ---  * 067    ---    ---    ---    ---  067       5   C     7',
 '35',
 'THEORY OF STRUCTURES IV',
 '2201929       ---    ---  * 016  * 028    ---    ---    ---    ---    ---    ---    ---    ---    ---  044 FFF   2   F     0',
 '0',
 'ENVIRONMENTAL SCIENCE',
 '2201930       ---    ---    ---    ---    ---  * 037    ---    ---    ---    ---    ---    ---    ---  037       2   B     8',
 '16',
 'HISTORY OF ARCH & CULTURE IV',
 '2201931       ---    ---    ---    ---    ---  * 025    ---    ---    ---    ---    ---    ---    ---  025       2   D     6',
 '12',
 'BUILDING SERVICES II [P]',
 '2201932       ---    ---  * 025  * 059    ---    ---    ---    ---    ---    ---    ---    ---    ---  084       2   A     9',
 '18',
 'BUILDING SERVICES II [SS]',
 '2201933       ---    ---    ---    ---    ---  * 034    ---    ---    ---    ---    ---    ---    ---  034       1   C     7',
 '7',
 'SITE SURVEY AND ANALYSIS',
 '2201934       ---    ---    ---    ---    ---  * 027    ---    ---    ---    ---    ---    ---    ---  027       2   D     6',
 '12',
 '    Fourth Semester SGPA : ----- Credits Earned/Total : 16/28',
 ' Total Credit Points: 116',
 'Second Year Result : Fail A.T.K.T.   Total Credits Earned : 44/56',
 ' % Ancillary   ^ Non-Credit Course  # O.4']

###**Testing for Year Pattern 2015**

In [ ]:
All_P19_YearDateWise_Student_Info_df1923[All_P19_YearDateWise_Student_Info_df1923['Course Pattern Year']=='2015 Pattern']

,PRN,Seat No,Name,Mother Name,Course Pattern Year,Ledger Year,Ledger Release Date,Student Info Lines
3017,1151518001047,1311,DOSHI ADITI AVINASH,SWATI,2015 Pattern,Apr-2023,28-Jul-2023,"[Savitribai Phule Pune University, 28-Jul-2023..."
3018,1151518001115,1371,NAIK JAIEE SUNIL,NANDA,2015 Pattern,Apr-2023,28-Jul-2023,"[.......Savitribai Phule Pune University, 28-J..."
3019,1151518001177,1279,AAKANKSHA PRASHANT MOHGAONKAR,ANUPRITA MOHGAONKAR,2015 Pattern,Apr-2023,28-Jul-2023,"[.......Savitribai Phule Pune University, 28-J..."
3020,1151518001559,1398,PRACHI M WADKAR,SWATI WADKAR,2015 Pattern,Apr-2023,28-Jul-2023,"[.......Savitribai Phule Pune University, 28-J..."
3021,1151518001689,1443,WANKHEDE MRUNMAYI NIKHIL,ANCHALA,2015 Pattern,Apr-2023,28-Jul-2023,"[.......Savitribai Phule Pune University, 28-J..."
...,...,...,...,...,...,...,...,...
3686,1151730338,1590,THOKE SHIVANI SUDHIR,GEETA,2015 Pattern,Apr-2020,21-Jul-2020,[................Savitribai Phule Pune Univers...
3687,1151730339,1039,BANG SHREYA RADHESHYAM,SNEHALATA,2015 Pattern,Apr-2020,21-Jul-2020,"[......., PRN: 1151730339 Seat no.: 1039 N..."
3688,1151730618,1186,JADWANI PRATIMA RAM,SANGEETA,2015 Pattern,Apr-2020,21-Jul-2020,"[................, PRN: 1151730618 Seat no.:..."
3689,1151731289,1292,LAHOTI HIMANI ANAND,SHEETAL,2015 Pattern,Apr-2020,21-Jul-2020,[.......Savitribai Phule Pune University21-Jul...
3690,1151731442,1082,DABIR AYESHA JAVID,RASHIDA,2015 Pattern,Apr-2020,21-Jul-2020,[.......Savitribai Phule Pune University21-Jul...

##**Grade Extraction for all 8 files Grades in one go**

In [ ]:
import re
import pandas as pd


# Define semester subject codes
semester_subject_codes = {
    'First Year First Semester': ['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917'],
    'First Year Second Semester': ['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A'],
    'Second Year Third Semester': ['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925', '2201935','2201935F'],
    'Second Year Fourth Semester': ['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934', '2201036', '2201936O','2201936F'],
    'Third Year Fifth Semester': ['3201935', '3201936', '3201937', '3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I'],
    'Third Year Sixth Semester': ['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D'],
    'Fourth Year Seventh Semester': ['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967', '4201967J'],
    'Forth Year Eighth Semester': ['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968', '4201968K'],
    'Fifth Year Ninth Semester': ['5201967'],
    'Fifth Year Tenth Semester': ['5201968', '5201969', '5201970'],
    'Extra Subject Eleventh Semester':['9201917','22999'],
}

# Flatten the dictionary to get a list of all subject codes
all_subject_codes = [code for codes in semester_subject_codes.values() for code in codes]

# Function to get semester name based on subject code
def get_semester_name(subject_code):
    for sem, codes in semester_subject_codes.items():
        if subject_code in codes:
            return sem
    return None


def parse_student_info(student_info_lines, prn_check):
    # [Your existing code for extracting PRN, Seat No, and Name]
    prn_pattern = r'PRN:\s*(\d+)'
    seat_pattern = r'Seat no.:\s*(\d+)'
    #name_pattern = r'NAME:\s*([A-Z\s]+)'
    name_pattern = r'NAME:\s*([A-Z\s]+?)(?= Mother| Father|$)'


    prn, seat_no, name = None, None, None
    for line in student_info_lines:
        # [Your existing code for extracting PRN, Seat No, and Name]
        if 'PRN:' in line:
            prn_match = re.search(prn_pattern, line)
            seat_match = re.search(seat_pattern, line)
            name_match = re.search(name_pattern, line)
            if prn_match:
                prn = prn_match.group(1)
            if seat_match:
                seat_no = seat_match.group(1)
            if name_match:
                name = name_match.group(1).strip()
            break
    if prn != prn_check:
        return None

    grades = []
    for line in student_info_lines:
        parts = line.split()
        if parts and parts[0] in all_subject_codes:
            merged_grades = []
            skip_next = False
            for i, part in enumerate(parts):
                if skip_next:
                    skip_next = False
                    continue

                if part == '*':
                    if i + 1 < len(parts):
                        merged_grades.append(part + parts[i + 1])
                        skip_next = True
                    else:
                        merged_grades.append(part)
                elif merged_grades and merged_grades[-1].isalpha() and part.isdigit():
                    merged_grades[-1] += part
                elif merged_grades and part == 'FFF':
                    merged_grades[-1] += part
                else:
                    merged_grades.append(part)

            grades.append(merged_grades + [None] * (len(columns) - 6 - len(merged_grades)))

    return {
        'PRN': prn,
        'Seat No': seat_no,
        'Name': name,
        'Grades': grades
    }

# Define your columns as per the expected output
columns = ['PRN', 'Seat No', 'Name', 'Course Pattern Year', 'Ledger Year', 'Ledger Release Date', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3',
           'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining']
All_P19_YearDateWise_Grades1618_Info_df1923 = pd.DataFrame(columns=columns)


# Assuming YearWise_Student_Info_df24 is defined and contains the necessary data
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    # [Your existing code for iterating over the DataFrame and parsing data]
    prn_check = row['PRN']
    student_info_lines = row['Student Info Lines']
    course_pattern_year = row['Course Pattern Year']
    ledger_year = row['Ledger Year']
    ledger_release_date= row['Ledger Release Date']

    parsed_data = parse_student_info(student_info_lines, prn_check)

    if parsed_data:
        student_df = pd.DataFrame(parsed_data['Grades'], columns=columns[6:])
        student_df['PRN'] = parsed_data['PRN']
        student_df['Seat No'] = parsed_data['Seat No']
        student_df['Name'] = parsed_data['Name']
        student_df['Ledger Release Date'] = ledger_release_date
        student_df['Course Pattern Year'] = course_pattern_year
        student_df['Ledger Year'] = ledger_year


        All_P19_YearDateWise_Grades1618_Info_df1923 = pd.concat([All_P19_YearDateWise_Grades1618_Info_df1923, student_df], ignore_index=True)

# Add 'Semester Name' column
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year with Semester Name'] = All_P19_YearDateWise_Grades1618_Info_df1923['Subject Code'].apply(get_semester_name)

#Subjects and their codes
#1201901

FY_sem1_code=['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917','1201917A', '1201917B', '1201917C']
FY_sem1_sub=['Basic Design', 'Building Construction & Materials I[P]', 'Building Construction & Materials I[SV]', 'Theory of Structures I', 'Architectural Graphics and Drawing I',
                'History of Arch & Culture I', 'Communication Skills', 'Workshop I', 'Audit Course','CRAFTS','CREATIVE WRITING','PERFORMING ARTS']

FY_sem2_code=['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A']
FY_sem2_sub=['Architectural Design I', 'Building Construction & Materials II[P]', 'Building Construction & Materials II[SV]', 'Theory of Structures II', 'Architectural Graphics and Drawing II',
                'History of Arch & Culture II', 'Fundamentals of Architecture', 'Workshop II', 'Audit Course', 'Audit Course']

SY_sem3_code=['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925','2201935','2201935F']
SY_sem3_sub=['Architectural Design II', 'Building Construction & Materials III[P]', 'Building Construction & Materials III[SV]', 'Theory of Structures III', 'Computer Aided Drawing and Graphics',
                'History of Arch & Culture III', 'Building Services I[P]', 'Building Services I[SS]', 'Climatology','Audit Course','Audit Course']

SY_sem4_code=['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934','2201036']
SY_sem4_sub=['Architectural Design III', 'Building Construction & Materials IV[P]', 'Building Construction & Materials IV[SV]', 'Theory of Structures IV', 'Environmental Sciences',
                'History of Arch & Culture IV', 'Building Services II[P]', 'Building Services II[SS]', 'Site Survey and Analysis','Audit Course']

TY_sem5_code=['3201935', '3201936', '3201937','3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I']
TY_sem5_sub=['Architectural Design IV', 'Building Construction & Materials V[P]', 'Building Construction & Materials V[SV]', 'Theory of Structures V', 'Landscape Architecture',
                'Elective I[Contemporary Architecture]', 'Building Services III[P]', 'Building Services III[SS]', 'Working Drawing I','Audit Course','Audit Course','Audit Course']

TY_sem6_code=['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D']
TY_sem6_sub=['Architectural Design V[SV]', 'Architectural Design V*[P]', 'Building Construction & Materials VI', 'Theory of Structures VI', 'Research In Architecture I',
                'Elective II', 'Building Services IV[P]', 'Building Services IV[SS]', 'Working Drawing II','Audit Course','Audit Course','Audit Course','Audit Course']

FOY_sem7_code=['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967','4201967J']
FOY_sem7_sub=['Architectural Design VI', 'Advanced Building Construction & Services I', 'Urban Studies I', 'Research In Architecture II',
                'Elective III', 'Quantity Surveying & Specification Writing I', 'Professional Practice', 'Audit Course','Audit Course']

FOY_sem8_code=['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968','4201968K']
FOY_sem8_sub=['Architectural Design VII', 'Advanced Building Construction & Services II', 'Urban Studies II', 'Elective IV',
                'Elective V', 'Quantity Surveying & Specification Writing II', 'Project Management', 'Audit Course','Audit Course']

FTY_sem9_code=['5201967']
FTY_sem9_sub=['Practical Training']

FTY_sem10_code=['5201968','5201969','5201970']
FTY_sem10_sub=['Architectural Design Project','Entrepreneurship Development','Elective VI*']

Extra_sem_code=['9201917','22999']
Extra_sem_sub=['PHYSICAL EDUCATION','DEMOCRACY ELECTION AND GOVERNANCE']


# Combine the lists into a list of pairs
code_sub_pairs = [
    (FY_sem1_code, FY_sem1_sub),
    (FY_sem2_code, FY_sem2_sub),
    (SY_sem3_code, SY_sem3_sub),
    (SY_sem4_code, SY_sem4_sub),
    (TY_sem5_code, TY_sem5_sub),
    (TY_sem6_code, TY_sem6_sub),
    (FOY_sem7_code, FOY_sem7_sub),
    (FOY_sem8_code, FOY_sem8_sub),
    (FTY_sem9_code, FTY_sem9_sub),
    (FTY_sem10_code, FTY_sem10_sub),
    (Extra_sem_code, Extra_sem_sub)
    # ... [Include other semester pairs here]
]

# Create the dictionary
subject_dict = {}
for code_list, sub_list in code_sub_pairs:
    for code, sub in zip(code_list, sub_list):
        subject_dict[code] = sub

# Print the dictionary
#for key, value in subject_dict.items():
    #print(f"{key}: {value}")


# Function to split the "Grades Semester Name" into two parts
def split_semester_name(name):
    if isinstance(name, str):
        parts = name.split()
        year_name = ' '.join(parts[:2]) if len(parts) >= 2 else None  # First two words or None
        semester_name = ' '.join(parts[-2:]) if len(parts) >= 2 else None  # Last two words or None
        return year_name, semester_name
    else:
        return None, None  # Default values for non-string entries

# Applying the function to create new columns in the existing DataFrame
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year Name'], All_P19_YearDateWise_Grades1618_Info_df1923['Grade Semester Name'] = zip(*All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year with Semester Name'].apply(split_semester_name))


# Map the subject codes to names and create a new column 'Subject Name'
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Subject Name'] = All_P19_YearDateWise_Grades1618_Info_df1923['Subject Code'].map(subject_dict)

# Displaying the first few rows of the final DataFrame
#print(All_P19_YearDateWise_Grades1618_Info_df1923.head())

###**Testing on All_P19_YearDateWise_Grades1618_Info_df1923**

In [ ]:
All_P19_YearDateWise_Grades1618_Info_df1923.columns

Index(['PRN', 'Seat No', 'Name', 'Course Pattern Year', 'Ledger Year',
       'Ledger Release Date', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2',
       'UEX', 'SS1', 'SS2', 'SS3', 'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot',
       'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining',
       'Grade Year with Semester Name', 'Grade Year Name',
       'Grade Semester Name', 'Grade Subject Name'],
      dtype='object')

###Testing for 1151919000946 on All_P19_YearDateWise_Grades_df1923

In [ ]:
temp_0946=All_P19_YearDateWise_Grades1618_Info_df1923[All_P19_YearDateWise_Grades1618_Info_df1923['PRN']=='1151919000946']
temp_0946

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
209,1151919000946,1205,THOMAS CELESTE HENRY,2019 Pattern,Oct-2021,09-Apr-2022,2201917,---,---,---,...,10,C7,70,None,None,None,Second Year Third Semester,Second Year,Third Semester,Architectural Design II
210,1151919000946,1205,THOMAS CELESTE HENRY,2019 Pattern,Oct-2021,09-Apr-2022,2201918,---,---,P027,...,2,B8,16,None,None,None,Second Year Third Semester,Second Year,Third Semester,Building Construction & Materials III[P]
211,1151919000946,1205,THOMAS CELESTE HENRY,2019 Pattern,Oct-2021,09-Apr-2022,2201919,---,---,---,...,5,C7,35,None,None,None,Second Year Third Semester,Second Year,Third Semester,Building Construction & Materials III[SV]
212,1151919000946,1205,THOMAS CELESTE HENRY,2019 Pattern,Oct-2021,09-Apr-2022,2201920,---,---,P023,...,2,C7,14,None,None,None,Second Year Third Semester,Second Year,Third Semester,Theory of Structures III
213,1151919000946,1205,THOMAS CELESTE HENRY,2019 Pattern,Oct-2021,09-Apr-2022,2201921,---,---,---,...,2,C7,14,None,None,None,Second Year Third Semester,Second Year,Third Semester,Computer Aided Drawing and Graphics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46864,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*022,*048,---,...,16,None,None,None,None,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46865,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,...,21,None,None,None,None,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46866,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,...,12,None,None,None,None,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46867,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,...,14,None,None,None,None,None,First Year First Semester,First Year,First Semester,Communication Skills
46868,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Workshop I

In [ ]:
oct_0946=temp_0946[temp_0946['Ledger Year']=='Oct-2019']
oct_0946.iloc[1].T

PRN                                                       1151919000946
Seat No                                                             508
Name                                               THOMAS CELESTE HENRY
Course Pattern Year                                        2019 Pattern
Ledger Year                                                    Oct-2019
Ledger Release Date                                         25/Jan/2020
Subject Code                                                    1201902
Int1                                                               *024
Ext1                                                               *046
Int2                                                                ---
Ext2                                                                ---
UEX                                                                 ---
SS1                                                                 ---
SS2                                                                 ---
SS3                                                                 ---
SV1                                                                 ---
SV2                                                                 ---
SV3                                                                 ---
SV4                                                                 070
SV5                                                                   2
Tot                                                                  B8
Tot_FFF                                                              16
Crd                                                                None
Grd                                                                None
GrdPnt                                                             None
CrdPnt                                                             None
Remaining                                                          None
Grade Year with Semester Name                 First Year First Semester
Grade Year Name                                              First Year
Grade Semester Name                                      First Semester
Grade Subject Name               Building Construction & Materials I[P]
Name: 46862, dtype: object

In [ ]:
oct_0946.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
46861,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201901,---,---,---,---,---,*163,---,---,---,---,---,163,10
46862,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201902,*024,*046,---,---,---,---,---,---,---,---,---,070,2
46863,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201903,---,---,---,---,---,---,*074,---,---,---,---,074,5
46864,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*022,*048,---,---,---,---,---,---,---,---,---,070,2
46865,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,---,*062,---,---,---,---,---,---,062,3
46866,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,*028,---,---,---,---,---,---,---,028,2
46867,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,*032,---,---,---,---,---,---,---,032,2
46868,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,---,*040,---,---,---,---,---,---,040FFF,2

In [ ]:
oct_0946.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
46861,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201901,---,---,---,---,---,*163,---,---,---,---,---,163,10
46862,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201902,*024,*046,---,---,---,---,---,---,---,---,---,070,2
46863,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201903,---,---,---,---,---,---,*074,---,---,---,---,074,5
46864,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*022,*048,---,---,---,---,---,---,---,---,---,070,2
46865,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,---,*062,---,---,---,---,---,---,062,3
46866,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,*028,---,---,---,---,---,---,---,028,2
46867,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,*032,---,---,---,---,---,---,---,032,2
46868,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,---,*040,---,---,---,---,---,---,040FFF,2

In [ ]:
oct_0946.iloc[:,20:33]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
46861,C7,70,None,None,None,None,None,First Year First Semester,First Year,First Semester,Basic Design
46862,B8,16,None,None,None,None,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46863,B8,40,None,None,None,None,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46864,B8,16,None,None,None,None,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46865,C7,21,None,None,None,None,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46866,D6,12,None,None,None,None,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46867,C7,14,None,None,None,None,None,First Year First Semester,First Year,First Semester,Communication Skills
46868,F0,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Workshop I

###**Testing for All_P19_YearDateWise_Grades1618_Info_df1923**

In [ ]:
All_P19_YearDateWise_Grades1618_Info_df1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,10,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,5,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,2,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48216,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*003,*004,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Theory of Structures I
48217,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
48218,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
48219,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Communication Skills
48220,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Workshop I

##**Transformation on All_P19_YearDateWise_Grades1618_Info_df1923 to get all the grades correctly**

* From All_P19_YearDateWise_Grades1618_Info_df1923 to Pat19_YearDateWise_Grad16_18_Info_df1923

In [ ]:
import pandas as pd

# Assuming All_P19_YearDateWise_Grades1618_Info_df1923 is your existing DataFrame
# Your existing code for copying the DataFrame
Pat19_YearDateWise_Grad16_18_Info_df1923 = All_P19_YearDateWise_Grades1618_Info_df1923.copy()

# Function to shift columns for specified ledger years
def shift_columns(row):
    if row['Ledger Year'] in ['Oct-2019', 'Apr-2020']:
        # Store values of Int1 and Ext1 to be used after the shift
        int1_value = row['Int1']
        ext1_value = row['Ext1']
        # Shift columns for Int1 and Ext1 to Int2 and Ext2, and so on
        for i in range(len(columns_to_shift) - 2, 1, -1):
            row[columns_to_shift[i]] = row[columns_to_shift[i - 2]]
        # Assign stored Int1 and Ext1 values to Int2 and Ext2
        row['Int2'] = int1_value
        row['Ext2'] = ext1_value
        # Set Int1 and Ext1 to 0 for the selected rows
        row['Int1'] = 0
        row['Ext1'] = 0
    return row

# Columns to shift
columns_to_shift = ['Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3', 'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining']

# Apply the shift_columns function to each row
Pat19_YearDateWise_Grad16_18_Info_df1923 = Pat19_YearDateWise_Grad16_18_Info_df1923.apply(shift_columns, axis=1)


# Step 2: Perform the transformations
# CrdPnt column gets values from Grd column
Pat19_YearDateWise_Grad16_18_Info_df1923['CrdPnt'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Grd']

# Grd column gets character values from Crd, and GrdPnt gets digit values
Pat19_YearDateWise_Grad16_18_Info_df1923['Grd'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Crd'].str.extract('([A-Za-z]+)')
Pat19_YearDateWise_Grad16_18_Info_df1923['GrdPnt'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Crd'].str.extract('(\d+)')

# Crd column gets values from Tot_FFF
Pat19_YearDateWise_Grad16_18_Info_df1923['Crd'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Tot_FFF']

# Optional: You might want to convert GrdPnt to numeric if it should be treated as a number
Pat19_YearDateWise_Grad16_18_Info_df1923['GrdPnt'] = pd.to_numeric(Pat19_YearDateWise_Grad16_18_Info_df1923['GrdPnt'], errors='coerce')


# Step 1: Extract 'FFF' part from the 'Tot' column
Pat19_YearDateWise_Grad16_18_Info_df1923['FFF_Part'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Tot'].str.extract('(FFF)')

# Step 2: Replace 'FFF' in 'Tot' column with an empty string
Pat19_YearDateWise_Grad16_18_Info_df1923['Tot'] = Pat19_YearDateWise_Grad16_18_Info_df1923['Tot'].str.replace('FFF', '', regex=True)

# Step 3: Assign the 'FFF' part to the 'Tot_FFF' column
Pat19_YearDateWise_Grad16_18_Info_df1923['Tot_FFF'] = Pat19_YearDateWise_Grad16_18_Info_df1923['FFF_Part']

# Optional: Remove the temporary 'FFF_Part' column
Pat19_YearDateWise_Grad16_18_Info_df1923.drop(['FFF_Part'], axis=1, inplace=True)

# Display the first few rows of the new DataFrame
#print(Pat19_YearDateWise_Grad16_18_Info_df1923.head())

In [ ]:
Pat19_YearDateWise_Grad16_18_Info_df1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48216,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,0,0,*003,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Theory of Structures I
48217,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,0,0,---,...,FFF,3,F,0.0,0,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
48218,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
48219,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Communication Skills
48220,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Workshop I

In [ ]:
Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year'].unique()

array(['Apr-2021', 'Oct-2021', 'Apr-2023', 'Apr-2022', 'Oct-2022',
       'Apr-2020', 'Oct-2019'], dtype=object)

####Temp 1151518001719 Apr-2021 --> Issue with next line shifted Grade

In [ ]:
temp_1719=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['PRN']=='1151518001719']
temp_1719

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33673,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201957,---,---,---,...,NaN,2,A,9.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
33674,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201958,---,---,*018,...,NaN,3,D,6.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Quantity Surveying & Specification Writing I
33675,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201959,---,---,*020,...,NaN,3,D,6.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Professional Practice
33676,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201967J,---,---,---,...,NaN,None,NaN,NaN,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Audit Course
33677,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,9201917,---,---,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

In [ ]:
temp_1719.iloc[:50,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,---,---,---,---,---,---,---,*115,---,---
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,*048,---,---,---,---,---,---,---,---,---
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,---,---,---,---,---,*067,---,---,---,---
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,*028,---,---,---,---,---,---,---,---,---
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,---,---,*037,---,---,---,---,---,---,---
5,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,---,---,*025,---,---,---,---,---,---,---
6,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*025,*059,---,---,---,---,---,---,---,---,---
7,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,---,---,*034,---,---,---,---,---,---,---
8,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,---,---,*027,---,---,---,---,---,---,---
89,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201917,---,---,---,---,---,---,---,---,---,---,P135,---,---
90,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201918,---,---,P023,P050,---,---,---,---,---,---,---,---,---
91,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201919,---,---,---,---,---,---,---,---,P058,---,---,---,---
92,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201920,---,---,P014,P032,---,---,---,---,---,---,---,---,---
93,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201921,---,---,---,---,---,P028,---,---,---,---,---,---,---
94,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201922,---,---,---,---,---,P039,---,---,---,---,---,---,---
95,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201923,---,---,P026,P062,---,---,---,---,---,---,---,---,---
96,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201924,---,---,---,---,---,P025,---,---,---,---,---,---,---
97,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201925,---,---,---,---,---,P035,---,---,---,---,---,---,---
98,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201926,---,---,---,---,---,---,---,---,---,---,*135,---,---
99,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201927,---,---,P024,P048,---,---,---,---,---,---,---,---,---
100,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201928,---,---,---,---,---,---,---,---,P067,---,---,---,---
101,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201929,---,---,P016,*032,---,---,---,---,---,---,---,---,---
102,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201930,---,---,---,---,---,P037,---,---,---,---,---,---,---
103,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201931,---,---,---,---,---,P025,---,---,---,---,---,---,---
104,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201932,---,---,P025,P059,---,---,---,---,---,---,---,---,---
105,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201933,---,---,---,---,---,P034,---,---,---,---,---,---,---
106,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201934,---,---,---,---,---,P027,---,---,---,---,---,---,---
107,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,2201936F,---,---,---,---,---,---,---,---,---,---,---,---,---
108,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201935,---,---,---,---,---,---,---,---,---,---,*AAA,---,---
109,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201936,---,---,*024,*052,---,---,---,---,---,---,---,---,---
110,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201937,---,---,---,---,---,---,---,---,*AAA,---,---,---,---
111,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201938,---,---,*029,*021,---,---,---,---,---,---,---,---,---
112,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201939,---,---,---,---,---,---,*AAA,---,---,---,---,---,---
113,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201940,---,---,---,---,---,---,*AAA,---,---,---,---,---,---
114,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201941,---,---,*023,*064,---,---,---,---,---,---,---,---,---
115,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201942,---,---,---,---,---,*AAA,---,---,---,---,---,---,---
116,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201943,---,---,---,---,---,---,*AAA,---,---,---,---,---,---
117,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,3201953I,---,---,---,---,---,---,---,---,---,---,---,---,---
118,1151518001719,917,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2021,09-Apr-2022,9201917,---,---,---,---,---,---,---,---,---,---,---,---,---
8518,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201935,---,---,---,---,---,---,---,---,---,---,*150,---,---
8519,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201936,---,---,P024,P052,---,---,---,---,---,---,---,---,---
8520,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201937,---,---,---,---,---,---,---,---,P055,---,---,---,---
8521,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201938,---,---,P029,P024,---,---,---,---,---,---,---,---,---
8522,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201939,---,---,---,---,---,---,P058,---,---,---,---,---,---
8523,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201940,---,---,---,---,---,---,P050,---,---,---,---,---,---
8524,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201941,---,---,P023,P064,---,---,---,---,---,---,---,---,---
8525,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201942,---,---,---,---,---,P025,---,---,---,---,---,---,---
8526,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201943,---,---,---,---,---,---,P050,---,---,---,---,---,---
8527,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201953I,---,---,---,---,---,---,---,---,---,---,---,---,---
8528,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,3201944,---,---,---,---,---,---,---,---,---,---,*126,---,---

In [ ]:
temp_1719.iloc[39:60,20:33]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
8518,150,NaN,10,C,7.0,70,None,Third Year Fifth Semester,Third Year,Fifth Semester,Architectural Design IV
8519,076,NaN,2,B,8.0,16,None,Third Year Fifth Semester,Third Year,Fifth Semester,Building Construction & Materials V[P]
8520,055,NaN,4,D,6.0,24,None,Third Year Fifth Semester,Third Year,Fifth Semester,Building Construction & Materials V[SV]
8521,053,NaN,2,D,6.0,12,None,Third Year Fifth Semester,Third Year,Fifth Semester,Theory of Structures V
8522,058,NaN,3,D,6.0,18,None,Third Year Fifth Semester,Third Year,Fifth Semester,Landscape Architecture
8523,050,NaN,2,D,6.0,12,None,Third Year Fifth Semester,Third Year,Fifth Semester,Elective I[Contemporary Architecture]
8524,087,NaN,2,A,9.0,18,None,Third Year Fifth Semester,Third Year,Fifth Semester,Building Services III[P]
8525,025,NaN,1,D,6.0,6,None,Third Year Fifth Semester,Third Year,Fifth Semester,Building Services III[SS]
8526,050,NaN,2,D,6.0,12,None,Third Year Fifth Semester,Third Year,Fifth Semester,Working Drawing I
8527,"""AC""",NaN,None,NaN,NaN,None,None,Third Year Fifth Semester,Third Year,Fifth Semester,Audit Course
8528,126,NaN,8,D,6.0,48,None,Third Year Sixth Semester,Third Year,Sixth Semester,Architectural Design V[SV]
8529,064,NaN,2,C,7.0,14,None,Third Year Sixth Semester,Third Year,Sixth Semester,Architectural Design V*[P]
8530,080,NaN,6,D,6.0,36,None,Third Year Sixth Semester,Third Year,Sixth Semester,Building Construction & Materials VI
8531,050,NaN,2,D,6.0,12,None,Third Year Sixth Semester,Third Year,Sixth Semester,Theory of Structures VI
8532,033,NaN,2,C,7.0,14,None,Third Year Sixth Semester,Third Year,Sixth Semester,Research In Architecture I
8533,057,NaN,3,D,6.0,18,None,Third Year Sixth Semester,Third Year,Sixth Semester,Elective II
8534,057,NaN,2,D,6.0,12,None,Third Year Sixth Semester,Third Year,Sixth Semester,Building Services IV[P]
8535,026,NaN,1,D,6.0,6,None,Third Year Sixth Semester,Third Year,Sixth Semester,Building Services IV[SS]
8536,054,NaN,2,D,6.0,12,None,Third Year Sixth Semester,Third Year,Sixth Semester,Working Drawing II
8537,"""AC""",NaN,None,NaN,NaN,None,None,Third Year Sixth Semester,Third Year,Sixth Semester,Audit Course
8538,172,NaN,11,D,6.0,66,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Architectural Design VI

####Temp 2023

In [ ]:
temp_23=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Apr-2023']
temp_23

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
8502,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201953,---,---,---,...,NaN,11,C,7.0,77,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Architectural Design VI
8503,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201954,---,---,---,...,NaN,4,D,6.0,24,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Advanced Building Construction & Services I
8504,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201955,---,---,---,...,NaN,3,C,7.0,21,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Urban Studies I
8505,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201956,---,---,---,...,NaN,2,D,6.0,12,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Research In Architecture II
8506,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201957,---,---,---,...,NaN,2,B,8.0,16,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23366,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201914,---,---,---,...,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
23367,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201915,---,---,---,...,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
23368,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201916,---,---,---,...,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,Workshop II
23369,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,22999,---,---,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,DEMOCRACY ELECTION AND GOVERNANCE
23370,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,9201917,---,---,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

In [ ]:
temp_23.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
8502,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201953,---,---,---,---,---,---,---,---,---,---,---,P205,---
8503,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201954,---,---,---,---,---,---,---,---,---,P084,---,---,---
8504,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201955,---,---,---,---,---,---,*060,---,---,---,---,---,---
8505,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201956,---,---,---,---,---,*028,---,---,---,---,---,---,---
8506,1151518001436,11176,ISHA GANDHI,2019 Pattern,Apr-2023,18-Sep-2023,4201957,---,---,---,---,---,P039,---,---,---,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
23366,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201914,---,---,---,---,---,*026,---,---,---,---,---,---,---
23367,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201915,---,---,---,---,---,*025,---,---,---,---,---,---,---
23368,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,1201916,---,---,---,---,---,---,*058,---,---,---,---,---,---
23369,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,22999,---,---,---,---,---,---,---,---,---,---,---,---,---
23370,1151922002999,11177,JADHAO SANIKA PRAFUL,2019 Pattern,Apr-2023,18-Sep-2023,9201917,---,---,---,---,---,---,---,---,---,---,---,---,---

In [ ]:
temp_23.iloc[:,20:32]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
8502,205,NaN,11,C,7.0,77,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Architectural Design VI
8503,084,NaN,4,D,6.0,24,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Advanced Building Construction & Services I
8504,060,NaN,3,C,7.0,21,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Urban Studies I
8505,028,NaN,2,D,6.0,12,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Research In Architecture II
8506,039,NaN,2,B,8.0,16,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
...,...,...,...,...,...,...,...,...,...,...,...
23366,026,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
23367,025,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
23368,058,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,Workshop II
23369,"*""B""",NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,DEMOCRACY ELECTION AND GOVERNANCE
23370,"""A""",NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

####Temp 2019

In [ ]:
temp_oct19=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Oct-2019']
temp_oct19

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
46861,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201901,0,0,---,...,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
46862,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201902,0,0,*024,...,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46863,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201903,0,0,---,...,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46864,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,0,0,*022,...,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46865,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,0,0,---,...,NaN,3,C,7.0,21,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48216,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,0,0,*003,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Theory of Structures I
48217,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,0,0,---,...,FFF,3,F,0.0,0,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
48218,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
48219,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Communication Skills
48220,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,0,0,---,...,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Workshop I

In [ ]:
temp_oct19.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
46861,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201901,0,0,---,---,---,---,---,*163,---,---,---,---,---
46862,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201902,0,0,*024,*046,---,---,---,---,---,---,---,---,---
46863,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201903,0,0,---,---,---,---,---,---,*074,---,---,---,---
46864,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,0,0,*022,*048,---,---,---,---,---,---,---,---,---
46865,1151919000946,508,THOMAS CELESTE HENRY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,0,0,---,---,---,---,*062,---,---,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48216,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,0,0,*003,*004,---,---,---,---,---,---,---,---,---
48217,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,0,0,---,---,---,---,*AAA,---,---,---,---,---,---
48218,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,0,0,---,---,---,*AAA,---,---,---,---,---,---,---
48219,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,0,0,---,---,---,*AAA,---,---,---,---,---,---,---
48220,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,0,0,---,---,---,---,*AAA,---,---,---,---,---,---

In [ ]:
temp_oct19.iloc[:50,20:32]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
46861,163,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
46862,070,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46863,074,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46864,070,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46865,062,NaN,3,C,7.0,21,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46866,028,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46867,032,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Communication Skills
46868,040,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Workshop I
46869,212,NaN,10,A,9.0,90,None,First Year First Semester,First Year,First Semester,Basic Design
46870,072,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46871,075,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46872,065,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46873,090,NaN,3,O,10.0,30,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46874,042,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46875,040,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Communication Skills
46876,087,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Workshop I
46877,188,NaN,10,B,8.0,80,None,First Year First Semester,First Year,First Semester,Basic Design
46878,073,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46879,077,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46880,063,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46881,077,NaN,3,B,8.0,24,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46882,034,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46883,041,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Communication Skills
46884,077,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Workshop I
46885,164,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
46886,075,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46887,068,NaN,5,C,7.0,35,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46888,056,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46889,068,NaN,3,C,7.0,21,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46890,029,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46891,034,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Communication Skills
46892,059,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,Workshop I
46893,176,NaN,10,B,8.0,80,None,First Year First Semester,First Year,First Semester,Basic Design
46894,056,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46895,070,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46896,077,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46897,075,NaN,3,B,8.0,24,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46898,041,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46899,035,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Communication Skills
46900,076,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Workshop I
46901,169,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
46902,057,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
46903,074,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
46904,059,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46905,070,NaN,3,B,8.0,24,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46906,033,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46907,034,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Communication Skills
46908,069,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Workshop I
46909,192,NaN,10,B,8.0,80,None,First Year First Semester,First Year,First Semester,Basic Design
46910,034,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]

####Temp 2020

In [ ]:
temp_apr20=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Apr-2020']
temp_apr20

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
44005,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201901,0,0,---,...,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
44006,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201902,0,0,P024,...,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
44007,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201903,0,0,---,...,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
44008,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201904,0,0,P022,...,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Theory of Structures I
44009,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201905,0,0,---,...,NaN,3,C,7.0,21,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46856,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201913,0,0,---,...,FFF,3,F,0.0,0,None,First Year Second Semester,First Year,Second Semester,Architectural Graphics and Drawing II
46857,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201914,0,0,---,...,FFF,2,F,0.0,0,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
46858,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201915,0,0,---,...,FFF,2,F,0.0,0,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
46859,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201916,0,0,---,...,FFF,2,F,0.0,0,None,First Year Second Semester,First Year,Second Semester,Workshop II
46860,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,9201917,0,0,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

In [ ]:
temp_apr20.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
44005,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201901,0,0,---,---,---,---,---,P163,---,---,---,---,---
44006,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201902,0,0,P024,P046,---,---,---,---,---,---,---,---,---
44007,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201903,0,0,---,---,---,---,---,---,P074,---,---,---,---
44008,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201904,0,0,P022,P048,---,---,---,---,---,---,---,---,---
44009,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,1201905,0,0,---,---,---,---,P062,---,---,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46856,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201913,0,0,---,---,---,---,*005,---,---,---,---,---,---
46857,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201914,0,0,---,---,---,*005,---,---,---,---,---,---,---
46858,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201915,0,0,---,---,---,*005,---,---,---,---,---,---,---
46859,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201916,0,0,---,---,---,---,*005,---,---,---,---,---,---
46860,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,9201917,0,0,---,---,---,---,---,---,---,---,---,---,---

In [ ]:
temp_apr20.iloc[:50,20:32]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
44005,163,NaN,10,C,7.0,70,None,First Year First Semester,First Year,First Semester,Basic Design
44006,070,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
44007,074,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
44008,070,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Theory of Structures I
44009,062,NaN,3,C,7.0,21,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
44010,028,NaN,2,D,6.0,12,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
44011,032,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Communication Skills
44012,040,FFF,2,F,0.0,0,None,First Year First Semester,First Year,First Semester,Workshop I
44013,180,NaN,10,B,8.0,80,None,First Year Second Semester,First Year,Second Semester,Architectural Design I
44014,072,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[P]
44015,066,NaN,5,C,7.0,35,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[SV]
44016,070,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,Theory of Structures II
44017,062,NaN,3,C,7.0,21,None,First Year Second Semester,First Year,Second Semester,Architectural Graphics and Drawing II
44018,031,NaN,2,C,7.0,14,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
44019,035,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
44020,058,NaN,2,D,6.0,12,None,First Year Second Semester,First Year,Second Semester,Workshop II
44021,"*""B""",NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION
44022,212,NaN,10,A,9.0,90,None,First Year First Semester,First Year,First Semester,Basic Design
44023,072,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
44024,075,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
44025,065,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Theory of Structures I
44026,090,NaN,3,O,10.0,30,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
44027,042,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
44028,040,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Communication Skills
44029,087,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Workshop I
44030,215,NaN,10,A,9.0,90,None,First Year Second Semester,First Year,Second Semester,Architectural Design I
44031,078,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[P]
44032,077,NaN,5,B,8.0,40,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[SV]
44033,080,NaN,2,A,9.0,18,None,First Year Second Semester,First Year,Second Semester,Theory of Structures II
44034,074,NaN,3,B,8.0,24,None,First Year Second Semester,First Year,Second Semester,Architectural Graphics and Drawing II
44035,036,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
44036,032,NaN,2,C,7.0,14,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
44037,067,NaN,2,C,7.0,14,None,First Year Second Semester,First Year,Second Semester,Workshop II
44038,"*""C""",NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION
44039,188,NaN,10,B,8.0,80,None,First Year First Semester,First Year,First Semester,Basic Design
44040,073,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[P]
44041,077,NaN,5,B,8.0,40,None,First Year First Semester,First Year,First Semester,Building Construction & Materials I[SV]
44042,063,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,Theory of Structures I
44043,077,NaN,3,B,8.0,24,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
44044,034,NaN,2,C,7.0,14,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
44045,041,NaN,2,A,9.0,18,None,First Year First Semester,First Year,First Semester,Communication Skills
44046,077,NaN,2,B,8.0,16,None,First Year First Semester,First Year,First Semester,Workshop I
44047,190,NaN,10,B,8.0,80,None,First Year Second Semester,First Year,Second Semester,Architectural Design I
44048,082,NaN,2,A,9.0,18,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[P]
44049,073,NaN,5,B,8.0,40,None,First Year Second Semester,First Year,Second Semester,Building Construction & Materials II[SV]
44050,085,NaN,2,A,9.0,18,None,First Year Second Semester,First Year,Second Semester,Theory of Structures II
44051,069,NaN,3,C,7.0,21,None,First Year Second Semester,First Year,Second Semester,Architectural Graphics and Drawing II
44052,036,NaN,2,B,8.0,16,None,First Year Second Semester,First Year,Second Semester,History of Arch & Culture II
44053,040,NaN,2,A,9.0,18,None,First Year Second Semester,First Year,Second Semester,Fundamentals of Architecture
44054,063,NaN,2,C,7.0,14,None,First Year Second Semester,First Year,Second Semester,Workshop II

####Temp 2021

In [ ]:
temp_apr21=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Apr-2021']
temp_apr21

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,History of Arch & Culture IV
85,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*024,...,NaN,2,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[P]
86,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,...,NaN,1,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[SS]
87,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,...,NaN,2,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Site Survey and Analysis
88,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,9201917,---,---,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

In [ ]:
temp_apr21.iloc[:,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,---,---,---,---,---,---,---,*115,---,---
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,*048,---,---,---,---,---,---,---,---,---
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,---,---,---,---,---,*067,---,---,---,---
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,*028,---,---,---,---,---,---,---,---,---
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,---,---,*037,---,---,---,---,---,---,---
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,---,---,*015,---,---,---,---,---,---,---
85,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*024,*038,---,---,---,---,---,---,---,---,---
86,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,---,---,*032,---,---,---,---,---,---,---
87,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,---,---,*032,---,---,---,---,---,---,---
88,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,9201917,---,---,---,---,---,---,---,---,---,---,---,---,---

In [ ]:
temp_apr21.iloc[:,20:32]

,Tot,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,115,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,072,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,067,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,044,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,037,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...
84,015,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,History of Arch & Culture IV
85,062,NaN,2,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[P]
86,032,NaN,1,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[SS]
87,032,NaN,2,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Site Survey and Analysis
88,"""C""",NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

###Testing for 1151518001719

In [ ]:
#temp_apr21=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Apr-2021']
temp_apr21_901=temp_apr21[temp_apr21['PRN']=='1151518001719']
temp_apr21_901

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
5,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,...,NaN,2,D,6.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,History of Arch & Culture IV
6,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*025,...,NaN,2,A,9.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[P]
7,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,...,NaN,1,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[SS]
8,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,...,NaN,2,D,6.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Site Survey and Analysis

In [ ]:
#temp_apr21=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['Ledger Year']=='Apr-2021']
temp_apr21_1719=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['PRN']=='1151518001719']
temp_apr21_1719

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,FFF,10,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,NaN,5,C,7.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,FFF,2,F,0.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,NaN,2,B,8.0,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33673,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201957,---,---,---,...,NaN,2,A,9.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
33674,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201958,---,---,*018,...,NaN,3,D,6.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Quantity Surveying & Specification Writing I
33675,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201959,---,---,*020,...,NaN,3,D,6.0,18,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Professional Practice
33676,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201967J,---,---,---,...,NaN,None,NaN,NaN,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Audit Course
33677,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,9201917,---,---,---,...,NaN,None,NaN,NaN,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

###**Testing for 2015 Pattern records**

In [ ]:
#1151919000984
temp_0984=Pat19_YearDateWise_Grad16_18_Info_df1923[Pat19_YearDateWise_Grad16_18_Info_df1923['PRN']=='1151518001054']
temp_0984

Empty DataFrame
Columns: [PRN, Seat No, Name, Course Pattern Year, Ledger Year, Ledger Release Date, Subject Code, Int1, Ext1, Int2, Ext2, UEX, SS1, SS2, SS3, SV1, SV2, SV3, SV4, SV5, Tot, Tot_FFF, Crd, Grd, GrdPnt, CrdPnt, Remaining, Grade Year with Semester Name, Grade Year Name, Grade Semester Name, Grade Subject Name]
Index: []

[0 rows x 31 columns]

In [ ]:
temp_Pat15_0984=temp_0984[temp_0984['Course Pattern Year']=='2015 Pattern']
temp_Pat15_0984

Empty DataFrame
Columns: [PRN, Seat No, Name, Course Pattern Year, Ledger Year, Ledger Release Date, Subject Code, Int1, Ext1, Int2, Ext2, UEX, SS1, SS2, SS3, SV1, SV2, SV3, SV4, SV5, Tot, Tot_FFF, Crd, Grd, GrdPnt, CrdPnt, Remaining, Grade Year with Semester Name, Grade Year Name, Grade Semester Name, Grade Subject Name]
Index: []

[0 rows x 31 columns]

In [ ]:
temp_Pat15_0984.iloc[:50,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
325,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201917,---,---,---,---,---,---,---,---,---,---,P198,---,---
326,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201918,---,---,P030,P052,---,---,---,---,---,---,---,---,---
327,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201919,---,---,---,---,---,---,---,---,P070,---,---,---,---
328,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201920,---,---,P023,P034,---,---,---,---,---,---,---,---,---
329,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201921,---,---,---,---,---,P034,---,---,---,---,---,---,---
330,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201922,---,---,---,---,---,P028,---,---,---,---,---,---,---
331,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201923,---,---,P023,P053,---,---,---,---,---,---,---,---,---
332,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201924,---,---,---,---,---,P043,---,---,---,---,---,---,---
333,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201925,---,---,---,---,---,P039,---,---,---,---,---,---,---
334,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201926,---,---,---,---,---,---,---,---,---,---,P204,---,---
335,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201927,---,---,P024,P055,---,---,---,---,---,---,---,---,---
336,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201928,---,---,---,---,---,---,---,---,P068,---,---,---,---
337,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201929,---,---,P023,P039,---,---,---,---,---,---,---,---,---
338,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201930,---,---,---,---,---,P035,---,---,---,---,---,---,---
339,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201931,---,---,---,---,---,P043,---,---,---,---,---,---,---
340,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201932,---,---,P021,P059,---,---,---,---,---,---,---,---,---
341,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201933,---,---,---,---,---,P033,---,---,---,---,---,---,---
342,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201934,---,---,---,---,---,P038,---,---,---,---,---,---,---
343,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,2201936F,---,---,---,---,---,---,---,---,---,---,---,---,---
344,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201935,---,---,---,---,---,---,---,---,---,---,*188,---,---
345,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201936,---,---,*028,*060,---,---,---,---,---,---,---,---,---
346,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201937,---,---,---,---,---,---,---,---,*075,---,---,---,---
347,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201938,---,---,*024,*034,---,---,---,---,---,---,---,---,---
348,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201939,---,---,---,---,---,---,*076,---,---,---,---,---,---
349,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201940,---,---,---,---,---,---,*073,---,---,---,---,---,---
350,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201941,---,---,*AAA,*063,---,---,---,---,---,---,---,---,---
351,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201942,---,---,---,---,---,*030,---,---,---,---,---,---,---
352,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201943,---,---,---,---,---,---,*064,---,---,---,---,---,---
353,1151919000984,959,KRITIKA AGRAWAL,2019 Pattern,Oct-2021,09-Apr-2022,3201953I,---,---,---,---,---,---,---,---,---,---,---,---,---
8748,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201953,---,---,---,---,---,---,---,---,---,---,---,P225,---
8749,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201954,---,---,---,---,---,---,---,---,---,P093,---,---,---
8750,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201955,---,---,---,---,---,---,P070,---,---,---,---,---,---
8751,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201956,---,---,---,---,---,P033,---,---,---,---,---,---,---
8752,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201957,---,---,---,---,---,P037,---,---,---,---,---,---,---
8753,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201958,---,---,P020,P035,---,---,---,---,---,---,---,---,---
8754,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201959,---,---,P017,P042,---,---,---,---,---,---,---,---,---
8755,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201967J,---,---,---,---,---,---,---,---,---,---,---,---,---
8756,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201960,---,---,---,---,---,---,---,---,---,---,---,*210,---
8757,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201961,---,---,---,---,---,---,---,---,---,*100,---,---,---
8758,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201962,---,---,---,---,---,---,*066,---,---,---,---,---,---
8759,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201963,---,---,---,---,---,*040,---,---,---,---,---,---,---
8760,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201964,---,---,---,---,---,*037,---,---,---,---,---,---,---
8761,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201965,---,---,*018,*040,---,---,---,---,---,---,---,---,---
8762,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201966,---,---,*016,*034,---,---,---,---,---,---,---,---,---
8763,1151919000984,11264,KRITIKA AGRAWAL,2019 Pattern,Apr-2023,18-Sep-2023,4201968K,---,---,---,---,---,---,---,---,---,---,---,---,---
23574,1151919000984,10938,KRITIKA AGRAWAL,2019 Pattern,Apr-2022,30-Aug-2022,3201935,---,---,---,---,---,---,---,---,---,---,P188,---,---
23575,1151919000984,10938,KRITIKA AGRAWAL,2019 Pattern,Apr-2022,30-Aug-2022,3201936,---,---,P028,P060,---,---,---,---,---,---,---,---,---
23576,1151919000984,10938,KRITIKA AGRAWAL,2019 Pattern,Apr-2022,30-Aug-2022,3201937,---,---,---,---,---,---,---,---,P075,---,---,---,---
23577,1151919000984,10938,KRITIKA AGRAWAL,2019 Pattern,Apr-2022,30-Aug-2022,3201938,---,---,P024,P034,---,---,---,---,---,---,---,---,---
23578,1151919000984,10938,KRITIKA AGRAWAL,2019 Pattern,Apr-2022,30-Aug-2022,3201939,---,---,---,---,---,---,P076,---,---,---,---,---,---

##**Final SGPA Records for all Four Ledgers**

* By refering **All_P19_YearDateWise_Student_Info_df1923**
* Getting SGPA records like Semester Name, Semester SGPA, Credits Earned, and Total Credits into **P19_YearDateWise_SGPA_Info_df1923**

In [ ]:
import pandas as pd
import re

# Function to parse student info lines and extract semester data
def parse_semester_info(student_info_lines):
    # Concatenate list elements into a single string
    info_str = ' '.join(student_info_lines)

    semester_data = []
    # Pattern to match semester information, including cases with "-----" as SGPA
    semester_info_pattern = r'(\w+ Semester) SGPA\s*:\s*([-\d.]+) Credits Earned/Total\s*:\s*(\d+/\d+)'
    # Pattern to match total credit points
    total_credit_points_pattern = r'Total Credit Points:\s*(\d+)'

    semester_matches = re.finditer(semester_info_pattern, info_str)
    total_credit_points_matches = re.findall(total_credit_points_pattern, info_str)

    for match, tcp in zip(semester_matches, total_credit_points_matches):
        # Check if SGPA is a valid number or a placeholder like "-----"
        sgpa = match.group(2).strip()
        sgpa = sgpa if sgpa.replace('.', '', 1).isdigit() else None

        semester_data.append({
            'SGPA Semester Name': match.group(1),
            'Semester SGPA': sgpa,
            'Semester Credits Earned': match.group(3),
            'Semester Total Credit Points': tcp
        })
    return semester_data

    # Initialize the list for the new DataFrame
new_data = []

# Loop through each row in the original DataFrame
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    student_semesters = parse_semester_info(row['Student Info Lines'])
    for sem_data in student_semesters:
        new_record = {
            'PRN': row['PRN'],
            'Seat No': row['Seat No'],
            'Name': row['Name'],
            'Course Pattern Year': row['Course Pattern Year'],
            'Ledger Year': row['Ledger Year'],
            'Ledger Release Date': row['Ledger Release Date'],
            **sem_data
        }
        new_data.append(new_record)

# Create the new DataFrame
P19_YearDateWise_SGPA_Info_df1923 = pd.DataFrame(new_data)

# Display the first few rows of the new DataFrame
#print(P19_YearDateWise_SGPA_Info_df1923.head())

###**Testing for P19_YearDateWise_SGPA_Info_df1923**

In [ ]:
P19_YearDateWise_SGPA_Info_df1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Second Semester,0.000,28/28,0
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,6.571,28/28,184
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,None,16/28,116
4,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12
...,...,...,...,...,...,...,...,...,...,...
5813,1151919002599,476,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,182
5814,1151919002605,460,PULLIWAR RIJUTA PRASAD,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.536,28/28,211
5815,1151919002612,452,PATIL TEJAL RAJARAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,212
5816,1151919002629,437,NASHRAH RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0
5817,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0

In [ ]:
#1151921002846
P19_YearDateWise_SGPA_Info_df1923[P19_YearDateWise_SGPA_Info_df1923['PRN']=='1151921002846']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points
1566,1151921002846,936,KEDARI SANKASHTI SHYAM,2019 Pattern,Oct-2021,09-Apr-2022,First Semester,7.036,28/28,197
2833,1151921002846,11233,KEDARI SANKASHTI SHYAM,2019 Pattern,Apr-2023,18-Sep-2023,Third Semester,5.964,28/28,167
2834,1151921002846,11233,KEDARI SANKASHTI SHYAM,2019 Pattern,Apr-2023,18-Sep-2023,Fourth Semester,None,26/28,177
4217,1151921002846,10915,KEDARI SANKASHTI SHYAM,2019 Pattern,Apr-2022,30-Aug-2022,First Semester,7.036,28/28,197
4218,1151921002846,10915,KEDARI SANKASHTI SHYAM,2019 Pattern,Apr-2022,30-Aug-2022,Second Semester,6.393,28/28,179
4897,1151921002846,10904,KEDARI SANKASHTI SHYAM,2019 Pattern,Oct-2022,08-Mar-2023,Third Semester,None,25/28,150

In [ ]:
#1151919001745

P19_YearDateWise_SGPA_Info_df1923[P19_YearDateWise_SGPA_Info_df1923['PRN']=='1151919001745']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points
174,1151919001745,806,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,6.429,28/28,180
175,1151919001745,806,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,None,18/28,125
925,1151919001745,1169,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,6.429,28/28,180
926,1151919001745,1169,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,6.607,28/28,185
927,1151919001745,1169,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,None,21/28,140
1765,1151919001745,11541,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2023,18-Sep-2023,Fifth Semester,6.536,28/28,183
1766,1151919001745,11541,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,None,20/28,126
1767,1151919001745,11541,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2023,18-Sep-2023,Seventh Semester,None,17/28,103
1768,1151919001745,11541,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2023,18-Sep-2023,Eighth Semester,None,11/28,73
3349,1151919001745,11148,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,None,23/28,152
3350,1151919001745,11148,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,None,8/28,50
4382,1151919001745,11139,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2022,08-Mar-2023,Fifth Semester,6.536,28/28,183
4383,1151919001745,11139,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2022,08-Mar-2023,Sixth Semester,None,20/28,126
4384,1151919001745,11139,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2022,08-Mar-2023,Seventh Semester,None,9/28,61
5470,1151919001745,379,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,None,26/28,172
5471,1151919001745,379,SIDDHI SUNIL SHINDE,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,6.250,28/28,175
5728,1151919001745,493,SIDDHI SUNIL SHINDE,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,172

In [ ]:
#1151919001028 This PRN is in both Oct-2022 Ledgers

P19_YearDateWise_SGPA_Info_df1923[P19_YearDateWise_SGPA_Info_df1923['PRN']=='1151919001028']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points
30,1151919001028,594,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,8.250,28/28,231
31,1151919001028,594,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,7.964,28/28,223
719,1151919001028,858,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,8.250,28/28,231
720,1151919001028,858,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,7.964,28/28,223
721,1151919001028,858,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,None,16/28,112
1601,1151919001028,11138,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2023,18-Sep-2023,Seventh Semester,7.000,28/28,196
1602,1151919001028,11138,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2023,18-Sep-2023,Eighth Semester,7.464,28/28,209
3197,1151919001028,10838,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,None,24/28,164
3198,1151919001028,10838,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,6.286,28/28,176
4248,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,08-Mar-2023,Fifth Semester,6.714,28/28,188
4249,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,08-Mar-2023,Sixth Semester,6.286,28/28,176
4250,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,08-Mar-2023,Seventh Semester,7.000,28/28,196
4902,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,04-May-2023,Fifth Semester,6.643,28/28,186
4903,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,6.286,28/28,176
4904,1151919001028,10831,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2022,04-May-2023,Seventh Semester,7.000,28/28,196
5328,1151919001028,266,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,7.714,28/28,216
5329,1151919001028,266,GADGIL NIKITA YOGESH,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,7.821,28/28,219
5656,1151919001028,379,GADGIL NIKITA YOGESH,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.714,28/28,216

##**Final SGPA and Year Result For Four Ledgers**
One more approch to get Smester SGPA and Year Result together without any mistakes

* By refering root dataframe **All_P19_YearDateWise_Student_Info_df1923**
* Getting output as SGPA and Year Result together into **P19_YearDateWise_SGPA_YearResult_Info_df1923** With all validations like PRN, Course Year, Ledger Year and Semeters.

In [ ]:
import pandas as pd
import re

def parse_info(student_info_lines):
    info_str = ' '.join(student_info_lines)

    semester_data = []
    year_data = []

    semester_info_pattern = r'(\w+ Semester) SGPA\s*:\s*([-\d.]+) Credits Earned/Total\s*:\s*(\d+/\d+)'
    total_credit_points_pattern = r'Total Credit Points:\s*(\d+)'
    year_info_pattern_with_result = r'(First|Second|Third|Fourth|Fifth) Year Result\s*:\s*(.*?)\s*Total Credits Earned\s*:\s*(\d+/\d+)'
    year_info_pattern_without_result = r'(First|Second|Third|Fourth|Fifth) Year Total Credits Earned\s*:\s*(\d+/\d+)'

    semester_matches = re.finditer(semester_info_pattern, info_str)
    total_credit_points_matches = re.findall(total_credit_points_pattern, info_str)
    year_matches_with_result = re.finditer(year_info_pattern_with_result, info_str)
    year_matches_without_result = re.finditer(year_info_pattern_without_result, info_str)

    for match in semester_matches:
        sgpa = match.group(2).strip()
        sgpa = sgpa if sgpa.replace('.', '', 1).isdigit() else None
        semester_data.append({
            'SGPA Semester Name': match.group(1),
            'Semester SGPA': sgpa,
            'Semester Credits Earned': match.group(3)
        })

    for tcp, sem_data in zip(total_credit_points_matches, semester_data):
        sem_data['Semester Total Credit Points'] = tcp

    for match in year_matches_with_result:
        year_data.append({
            'Year Result Year Name': match.group(1) + " Year",
            'Year Result': match.group(2).strip(),
            'Year Total Credits Earned': match.group(3)
        })

    for match in year_matches_without_result:
        year_data.append({
            'Year Result Year Name': match.group(1) + " Year",
            'Year Result': None,
            'Year Total Credits Earned': match.group(2)
        })

    return semester_data, year_data

def match_year_result_to_semesters(semesters, years, prn, course_year, ledger_year):
    semester_to_year_map = {
        "First Semester": "First Year",
        "Second Semester": "First Year",
        "Third Semester": "Second Year",
        "Fourth Semester": "Second Year",
        "Fifth Semester": "Third Year",
        "Sixth Semester": "Third Year",
        "Seventh Semester": "Fourth Year",
        "Eighth Semester": "Fourth Year",
        "Ninth Semester": "Fifth Year",
        "Tenth Semester": "Fifth Year",
    }

    year_result_dict = {(year_info['Year Result Year Name'], prn, course_year, ledger_year): year_info
                        for year_info in years}

    for sem in semesters:
        year_key = (semester_to_year_map.get(sem['SGPA Semester Name'], ''), prn, course_year, ledger_year)
        if year_key in year_result_dict:
            sem.update(year_result_dict[year_key])

new_data = []

for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    semester_info, year_info = parse_info(row['Student Info Lines'])

    match_year_result_to_semesters(semester_info, year_info, row['PRN'], row['Course Pattern Year'], row['Ledger Year'])

    for sem_data in semester_info:
        new_record = {
            'PRN': row['PRN'],
            'Seat No': row.get('Seat No', 'N/A'),
            'Name': row['Name'],
            'Course Pattern Year': row['Course Pattern Year'],
            'Ledger Year': row['Ledger Year'],
            'Ledger Release Date': row['Ledger Release Date'],
            **sem_data
        }
        new_data.append(new_record)

P19_YearDateWise_SGPA_YearResult_Info_df1923 = pd.DataFrame(new_data)
#print(P19_YearDateWise_SGPA_YearResult_Info_df1923.head())

###**Testing for P19_YearDateWise_SGPA_YearResult__Info_df1923**

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Second Semester,0.000,28/28,0,First Year,None,56/56
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,6.571,28/28,184,Second Year,Fail A.T.K.T.,44/56
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,None,16/28,116,Second Year,Fail A.T.K.T.,44/56
4,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5813,1151919002599,476,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,182,NaN,NaN,NaN
5814,1151919002605,460,PULLIWAR RIJUTA PRASAD,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.536,28/28,211,NaN,NaN,NaN
5815,1151919002612,452,PATIL TEJAL RAJARAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,212,NaN,NaN,NaN
5816,1151919002629,437,NASHRAH RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN
5817,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923[P19_YearDateWise_SGPA_YearResult_Info_df1923['PRN']=='1151518002587']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned
8,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
9,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,Second Semester,0.000,28/28,0,First Year,None,56/56
10,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,None,26/28,156,Second Year,Fail A.T.K.T.,35/56
11,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,None,9/28,57,Second Year,Fail A.T.K.T.,35/56
692,1151518002587,819,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,6.071,28/28,170,Second Year,Fail A.T.K.T.,44/56
693,1151518002587,819,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,None,16/28,103,Second Year,Fail A.T.K.T.,44/56
694,1151518002587,819,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,None,4/28,26,NaN,NaN,NaN
1575,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2023,18-Sep-2023,Third Semester,6.071,28/28,170,Second Year,Fail A.T.K.T.,44/56
1576,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2023,18-Sep-2023,Fourth Semester,None,16/28,103,Second Year,Fail A.T.K.T.,44/56
1577,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2023,18-Sep-2023,Fifth Semester,None,10/28,63,Third Year,Fail,14/56
1578,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,None,4/28,24,Third Year,Fail,14/56
3175,1151518002587,10800,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2022,30-Aug-2022,Third Semester,6.071,28/28,170,Second Year,Fail A.T.K.T.,44/56
3176,1151518002587,10800,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2022,30-Aug-2022,Fourth Semester,None,16/28,103,Second Year,Fail A.T.K.T.,44/56
3177,1151518002587,10800,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,None,7/28,45,Third Year,Fail,7/56
3178,1151518002587,10800,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,None,0/28,0,Third Year,Fail,7/56
4224,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,08-Mar-2023,Third Semester,6.071,28/28,170,Second Year,Fail A.T.K.T.,44/56
4225,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,08-Mar-2023,Fourth Semester,None,16/28,103,Second Year,Fail A.T.K.T.,44/56
4226,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,08-Mar-2023,Fifth Semester,None,10/28,63,Third Year,Fail,10/56
4227,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,08-Mar-2023,Sixth Semester,None,0/28,0,Third Year,Fail,10/56
4898,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,04-May-2023,Third Semester,6.071,28/28,170,Second Year,Fail A.T.K.T.,44/56
4899,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,04-May-2023,Fourth Semester,None,16/28,103,Second Year,Fail A.T.K.T.,44/56
4900,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,04-May-2023,Fifth Semester,None,10/28,63,Third Year,Fail,10/56
4901,1151518002587,10793,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,0/28,0,Third Year,Fail,10/56

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923['SGPA Semester Name'].unique()

array(['First Semester', 'Second Semester', 'Third Semester',
       'Fourth Semester', 'Fifth Semester', 'Seventh Semester',
       'Eighth Semester', 'Sixth Semester'], dtype=object)

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923[P19_YearDateWise_SGPA_YearResult_Info_df1923['SGPA Semester Name']=='First Semester']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
4,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
8,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
12,1151518002600,751,RAJURKAR JUI AJAY,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
58,1151919001165,604,GOJAMGUNDE NISHIGANDHA ABHIJEET,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.821,28/28,191,First Year,None,56/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5813,1151919002599,476,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,182,NaN,NaN,NaN
5814,1151919002605,460,PULLIWAR RIJUTA PRASAD,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.536,28/28,211,NaN,NaN,NaN
5815,1151919002612,452,PATIL TEJAL RAJARAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,212,NaN,NaN,NaN
5816,1151919002629,437,NASHRAH RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN
5817,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923[P19_YearDateWise_SGPA_YearResult_Info_df1923['SGPA Semester Name']=='First Semester']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
4,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
8,1151518002587,570,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
12,1151518002600,751,RAJURKAR JUI AJAY,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56
58,1151919001165,604,GOJAMGUNDE NISHIGANDHA ABHIJEET,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.821,28/28,191,First Year,None,56/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
5813,1151919002599,476,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,182,NaN,NaN,NaN
5814,1151919002605,460,PULLIWAR RIJUTA PRASAD,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.536,28/28,211,NaN,NaN,NaN
5815,1151919002612,452,PATIL TEJAL RAJARAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,212,NaN,NaN,NaN
5816,1151919002629,437,NASHRAH RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN
5817,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN

In [ ]:
P19_YearDateWise_SGPA_YearResult_Info_df1923[P19_YearDateWise_SGPA_YearResult_Info_df1923['SGPA Semester Name']=='Sixth Semester']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned
1570,1151518001719,11210,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,6.143,28/28,172,Third Year,None,56/56
1578,1151518002587,11082,DAMSE YOGESHWARI DASHARATH,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,None,4/28,24,Third Year,Fail,14/56
1582,1151730262,11037,BHARATI AVANTIKA MAHENDRA,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,None,16/28,96,Third Year,Fail A.T.K.T.,28/56
1592,1151919000977,11107,DHAPARE AABHA VINAY,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,6.857,28/28,192,Third Year,None,56/56
1612,1151919001073,11053,BIRNALE ANUSHKA AJITKUMAR,2019 Pattern,Apr-2023,18-Sep-2023,Sixth Semester,6.607,28/28,185,Third Year,None,56/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...
4911,1151919001707,11089,SAKSHI BIRADAR,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,17/28,116,Third Year,Fail A.T.K.T.,41/56
4913,1151919001844,11093,SALUNKE BHAKTI RAHUL,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,10/28,65,Third Year,Fail,26/56
4917,1151919001875,11160,TANISHKA SHIVAJI DHAGE,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,3/28,18,Third Year,Fail,5/56
4921,1151919002018,10954,MALANI SNEHAL RAJESHKUMARJI,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,12/28,77,Third Year,Fail,26/56
4934,1151919002599,11091,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2022,04-May-2023,Sixth Semester,None,18/28,109,Third Year,Fail A.T.K.T.,46/56

#**Dashboard Data Frames**

###**Screen1 dataframe**

In [ ]:
EightLedger_SGPA_YearResult_df_merge=P19_YearDateWise_SGPA_YearResult_Info_df1923.copy()
EightLedger_SGPA_YearResult_df_merge = EightLedger_SGPA_YearResult_df_merge.rename(columns={
    'SGPA Semester Name': 'Grade Semester Name',
    'Year Result Year Name': 'Grade Year Name'
})

key_columns1 = ['PRN', 'Seat No', 'Grade Semester Name', 'Grade Year Name', 'Ledger Year', 'Ledger Release Date']  # Adjust the column names if they are different in your dataframes

Screen1_df1923 = pd.merge(
    Pat19_YearDateWise_Grad16_18_Info_df1923,
    EightLedger_SGPA_YearResult_df_merge,
    on=key_columns1,
    how='inner'
)
Screen1_df1923=Screen1_df1923.drop(columns=['Name_y', 'Course Pattern Year_y','Remaining', 'Grade Year with Semester Name'],axis=1)
#print(Screen1_df1923.head())

In [ ]:
Screen1_df1923

,PRN,Seat No,Name_x,Course Pattern Year_x,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,GrdPnt,CrdPnt,Grade Year Name,Grade Semester Name,Grade Subject Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result,Year Total Credits Earned
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,0.0,None,Second Year,Fourth Semester,Architectural Design III,None,16/28,116,Fail A.T.K.T.,44/56
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,8.0,None,Second Year,Fourth Semester,Building Construction & Materials IV[P],None,16/28,116,Fail A.T.K.T.,44/56
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,7.0,None,Second Year,Fourth Semester,Building Construction & Materials IV[SV],None,16/28,116,Fail A.T.K.T.,44/56
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,0.0,None,Second Year,Fourth Semester,Theory of Structures IV,None,16/28,116,Fail A.T.K.T.,44/56
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,8.0,None,Second Year,Fourth Semester,Environmental Sciences,None,16/28,116,Fail A.T.K.T.,44/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33624,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201912,0,0,*AAA,...,0.0,0,First Year,Second Semester,Theory of Structures II,None,0/28,0,Fail,0/56
33625,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201913,0,0,---,...,0.0,0,First Year,Second Semester,Architectural Graphics and Drawing II,None,0/28,0,Fail,0/56
33626,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201914,0,0,---,...,0.0,0,First Year,Second Semester,History of Arch & Culture II,None,0/28,0,Fail,0/56
33627,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201915,0,0,---,...,0.0,0,First Year,Second Semester,Fundamentals of Architecture,None,0/28,0,Fail,0/56
33628,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201916,0,0,---,...,0.0,0,First Year,Second Semester,Workshop II,None,0/28,0,Fail,0/56

###**Screen2 dataframe**

In [ ]:
key_columns2 = ['PRN', 'Seat No', 'Ledger Year', 'Ledger Release Date']
merged_df_inner2 = pd.merge(
    Pat19_YearDateWise_Grad16_18_Info_df1923,
    All_P19_YearDateWise_Student_Info_df1923,
    on=key_columns2,
    how='inner'
)
merged_df_inner2=merged_df_inner2.drop(columns=['Remaining','Student Info Lines', 'Grade Year with Semester Name','Name_y', 'Course Pattern Year_y'])
#merged_df_inner2
#print(merged_df_inner2.head())
key_columns2_1 = ['PRN', 'Seat No', 'Grade Semester Name', 'Grade Year Name', 'Ledger Year', 'Ledger Release Date']
#key_columns2_1 = ['PRN', 'Seat No','Ledger Year']
screen2_df1923= pd.merge(
    merged_df_inner2,
    EightLedger_SGPA_YearResult_df_merge,
    on=key_columns2_1,
    how='inner'
)
#screen2_df1923=screen2_df.drop(columns=['Name', 'Course Pattern Year'], axis=1)
#print(screen2_df1923.head())

In [ ]:
screen2_df1923

,PRN,Seat No,Name_x,Course Pattern Year_x,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Grade Semester Name,Grade Subject Name,Mother Name,Name,Course Pattern Year,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result,Year Total Credits Earned
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,Fourth Semester,Architectural Design III,RADHA,KABRA SAKSHI GOVIND,2019 Pattern,None,16/28,116,Fail A.T.K.T.,44/56
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,Fourth Semester,Building Construction & Materials IV[P],RADHA,KABRA SAKSHI GOVIND,2019 Pattern,None,16/28,116,Fail A.T.K.T.,44/56
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,Fourth Semester,Building Construction & Materials IV[SV],RADHA,KABRA SAKSHI GOVIND,2019 Pattern,None,16/28,116,Fail A.T.K.T.,44/56
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,Fourth Semester,Theory of Structures IV,RADHA,KABRA SAKSHI GOVIND,2019 Pattern,None,16/28,116,Fail A.T.K.T.,44/56
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,Fourth Semester,Environmental Sciences,RADHA,KABRA SAKSHI GOVIND,2019 Pattern,None,16/28,116,Fail A.T.K.T.,44/56
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33624,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201912,0,0,*AAA,...,Second Semester,Theory of Structures II,ANJUM RAHIM,NASHRAH RAHIM,2019 Pattern,None,0/28,0,Fail,0/56
33625,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201913,0,0,---,...,Second Semester,Architectural Graphics and Drawing II,ANJUM RAHIM,NASHRAH RAHIM,2019 Pattern,None,0/28,0,Fail,0/56
33626,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201914,0,0,---,...,Second Semester,History of Arch & Culture II,ANJUM RAHIM,NASHRAH RAHIM,2019 Pattern,None,0/28,0,Fail,0/56
33627,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201915,0,0,---,...,Second Semester,Fundamentals of Architecture,ANJUM RAHIM,NASHRAH RAHIM,2019 Pattern,None,0/28,0,Fail,0/56
33628,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,1201916,0,0,---,...,Second Semester,Workshop II,ANJUM RAHIM,NASHRAH RAHIM,2019 Pattern,None,0/28,0,Fail,0/56

#**12th Jan 2024**
April 2021 pdf has differnt format  so not getting all the grades correctly,

In [ ]:
def parse_student_info(student_info_lines, prn_check):
    # [Your existing code for extracting PRN, Seat No, and Name]
    prn_pattern = r'PRN:\s*(\d+)'
    seat_pattern = r'Seat no.:\s*(\d+)'
    name_pattern = r'NAME:\s*([A-Z\s]+?)(?= Mother| Father|$)'

    prn, seat_no, name = None, None, None
    for line in student_info_lines:
        # [Your existing code for extracting PRN, Seat No, and Name]
        if 'PRN:' in line:
            prn_match = re.search(prn_pattern, line)
            seat_match = re.search(seat_pattern, line)
            name_match = re.search(name_pattern, line)
            if prn_match:
                prn = prn_match.group(1)
            if seat_match:
                seat_no = seat_match.group(1)
            if name_match:
                name = name_match.group(1).strip()
            break
    if prn != prn_check:
        return None

    grades = []
    subject_code_pattern = r'\d{7}'  # Adjust the pattern based on your subject code format

    for i, line in enumerate(student_info_lines):
        parts = line.split()

        # Check if the line contains a subject code
        if any(re.match(subject_code_pattern, part) for part in parts):
            # Extract grades from the next 18 lines
            grades_lines = student_info_lines[i + 1:i + 19]
            merged_grades = []

            # Process grades_lines to extract merged_grades
            skip_next = False
            for i, part in enumerate(parts):
                if skip_next:
                    skip_next = False
                    continue

                if part == '*':
                    if i + 1 < len(parts):
                        merged_grades.append(part + parts[i + 1])
                        skip_next = True
                    else:
                        merged_grades.append(part)
                elif merged_grades and merged_grades[-1].isalpha() and part.isdigit():
                    merged_grades[-1] += part
                elif merged_grades and part == 'FFF':
                    merged_grades[-1] += part
                else:
                    merged_grades.append(part)

            grades.append(merged_grades + [None] * (len(columns) - 6 - len(merged_grades)))

    return {
        'PRN': prn,
        'Seat No': seat_no,
        'Name': name,
        'Grades': grades
    }

In [ ]:
import re
import pandas as pd


# Define semester subject codes
semester_subject_codes = {
    'First Year First Semester': ['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917','1201917A', '1201917B', '1201917C'],
    'First Year Second Semester': ['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A'],
    'Second Year Third Semester': ['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925', '2201935','2201935F'],
    'Second Year Fourth Semester': ['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934', '2201036', '2201936O','2201936F'],
    'Third Year Fifth Semester': ['3201935', '3201936', '3201937', '3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I'],
    'Third Year Sixth Semester': ['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D'],
    'Fourth Year Seventh Semester': ['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967', '4201967J'],
    'Forth Year Eighth Semester': ['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968', '4201968K'],
    'Fifth Year Ninth Semester': ['5201967'],
    'Fifth Year Tenth Semester': ['5201968', '5201969', '5201970'],
    'Extra Subject Eleventh Semester':['9201917','22999'],
}

# Flatten the dictionary to get a list of all subject codes
all_subject_codes = [code for codes in semester_subject_codes.values() for code in codes]

# Function to get semester name based on subject code
def get_semester_name(subject_code):
    for sem, codes in semester_subject_codes.items():
        if subject_code in codes:
            return sem
    return None

def parse_student_info(student_info_lines, prn_check, ledger_year, ledger_release_date):
    prn_pattern = r'PRN:\s*(\d+)'
    seat_pattern = r'Seat no.:\s*(\d+)'
    name_pattern = r'NAME:\s*([A-Z\s]+?)(?= Mother| Father|$)'

    prn, seat_no, name = None, None, None
    for line in student_info_lines:
        if 'PRN:' in line:
            prn_match = re.search(prn_pattern, line)
            seat_match = re.search(seat_pattern, line)
            name_match = re.search(name_pattern, line)
            if prn_match:
                prn = prn_match.group(1)
            if seat_match:
                seat_no = seat_match.group(1)
            if name_match:
                name = name_match.group(1).strip()
            break
    if prn != prn_check:
        return None

    grades = []
    for line in student_info_lines:
        parts = line.split()
        if parts and parts[0] in all_subject_codes:
            merged_grades = []
            skip_next = False
            for i, part in enumerate(parts):
                if skip_next:
                    skip_next = False
                    continue

                if part == '*':
                    if i + 1 < len(parts):
                        merged_grades.append(part + parts[i + 1])
                        skip_next = True
                    else:
                        merged_grades.append(part)
                elif merged_grades and merged_grades[-1].isalpha() and part.isdigit():
                    merged_grades[-1] += part
                elif merged_grades and part == 'FFF':
                    merged_grades[-1] += part
                else:
                    merged_grades.append(part)

            grades.append(merged_grades + [None] * (len(columns) - 6 - len(merged_grades)))

    return {
        'PRN': prn,
        'Seat No': seat_no,
        'Name': name,
        'Ledger Year': ledger_year,
        'Ledger Release Date': ledger_release_date,
        'Grades': grades
    }

# Define your columns as per the expected output
columns = ['PRN', 'Seat No', 'Name', 'Course Pattern Year', 'Ledger Year', 'Ledger Release Date', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3',
           'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining']
All_P19_apr21_Grd18_df1923 = pd.DataFrame(columns=columns)

# Assuming YearWise_Student_Info_df24 is defined and contains the necessary data
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    prn_check = row['PRN']
    student_info_lines = row['Student Info Lines']
    course_pattern_year = row['Course Pattern Year']
    ledger_year = row['Ledger Year']
    ledger_release_date = row['Ledger Release Date']

    parsed_data = parse_student_info(student_info_lines, prn_check, ledger_year, ledger_release_date)

    if parsed_data:
        student_df = pd.DataFrame(parsed_data['Grades'], columns=columns[6:])
        student_df['PRN'] = parsed_data['PRN']
        student_df['Seat No'] = parsed_data['Seat No']
        student_df['Name'] = parsed_data['Name']
        student_df['Ledger Release Date'] = parsed_data['Ledger Release Date']
        student_df['Course Pattern Year'] = course_pattern_year
        student_df['Ledger Year'] = parsed_data['Ledger Year']

        All_P19_apr21_Grd18_df1923 = pd.concat([All_P19_apr21_Grd18_df1923, student_df], ignore_index=True)



# Add 'Semester Name' column
All_P19_apr21_Grd18_df1923['Grade Year with Semester Name'] = All_P19_apr21_Grd18_df1923['Subject Code'].apply(get_semester_name)

#Subjects and their codes
#1201901

FY_sem1_code=['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917','1201917A', '1201917B', '1201917C']
FY_sem1_sub=['Basic Design', 'Building Construction & Materials I[P]', 'Building Construction & Materials I[SV]', 'Theory of Structures I', 'Architectural Graphics and Drawing I',
                'History of Arch & Culture I', 'Communication Skills', 'Workshop I', 'Audit Course','CRAFTS','CREATIVE WRITING','PERFORMING ARTS']

FY_sem2_code=['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A']
FY_sem2_sub=['Architectural Design I', 'Building Construction & Materials II[P]', 'Building Construction & Materials II[SV]', 'Theory of Structures II', 'Architectural Graphics and Drawing II',
                'History of Arch & Culture II', 'Fundamentals of Architecture', 'Workshop II', 'Audit Course', 'Audit Course']

SY_sem3_code=['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925','2201935','2201935F']
SY_sem3_sub=['Architectural Design II', 'Building Construction & Materials III[P]', 'Building Construction & Materials III[SV]', 'Theory of Structures III', 'Computer Aided Drawing and Graphics',
                'History of Arch & Culture III', 'Building Services I[P]', 'Building Services I[SS]', 'Climatology','Audit Course','Audit Course']

SY_sem4_code=['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934','2201036']
SY_sem4_sub=['Architectural Design III', 'Building Construction & Materials IV[P]', 'Building Construction & Materials IV[SV]', 'Theory of Structures IV', 'Environmental Sciences',
                'History of Arch & Culture IV', 'Building Services II[P]', 'Building Services II[SS]', 'Site Survey and Analysis','Audit Course']

TY_sem5_code=['3201935', '3201936', '3201937','3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I']
TY_sem5_sub=['Architectural Design IV', 'Building Construction & Materials V[P]', 'Building Construction & Materials V[SV]', 'Theory of Structures V', 'Landscape Architecture',
                'Elective I[Contemporary Architecture]', 'Building Services III[P]', 'Building Services III[SS]', 'Working Drawing I','Audit Course','Audit Course','Audit Course']

TY_sem6_code=['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D']
TY_sem6_sub=['Architectural Design V[SV]', 'Architectural Design V*[P]', 'Building Construction & Materials VI', 'Theory of Structures VI', 'Research In Architecture I',
                'Elective II', 'Building Services IV[P]', 'Building Services IV[SS]', 'Working Drawing II','Audit Course','Audit Course','Audit Course','Audit Course']

FOY_sem7_code=['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967','4201967J']
FOY_sem7_sub=['Architectural Design VI', 'Advanced Building Construction & Services I', 'Urban Studies I', 'Research In Architecture II',
                'Elective III', 'Quantity Surveying & Specification Writing I', 'Professional Practice', 'Audit Course','Audit Course']

FOY_sem8_code=['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968','4201968K']
FOY_sem8_sub=['Architectural Design VII', 'Advanced Building Construction & Services II', 'Urban Studies II', 'Elective IV',
                'Elective V', 'Quantity Surveying & Specification Writing II', 'Project Management', 'Audit Course','Audit Course']

FTY_sem9_code=['5201967']
FTY_sem9_sub=['Practical Training']

FTY_sem10_code=['5201968','5201969','5201970']
FTY_sem10_sub=['Architectural Design Project','Entrepreneurship Development','Elective VI*']

Extra_sem_code=['9201917','22999']
Extra_sem_sub=['PHYSICAL EDUCATION','DEMOCRACY ELECTION AND GOVERNANCE']


# Combine the lists into a list of pairs
code_sub_pairs = [
    (FY_sem1_code, FY_sem1_sub),
    (FY_sem2_code, FY_sem2_sub),
    (SY_sem3_code, SY_sem3_sub),
    (SY_sem4_code, SY_sem4_sub),
    (TY_sem5_code, TY_sem5_sub),
    (TY_sem6_code, TY_sem6_sub),
    (FOY_sem7_code, FOY_sem7_sub),
    (FOY_sem8_code, FOY_sem8_sub),
    (FTY_sem9_code, FTY_sem9_sub),
    (FTY_sem10_code, FTY_sem10_sub),
    (Extra_sem_code, Extra_sem_sub)
    # ... [Include other semester pairs here]
]

# Create the dictionary
subject_dict = {}
for code_list, sub_list in code_sub_pairs:
    for code, sub in zip(code_list, sub_list):
        subject_dict[code] = sub

# Print the dictionary
#for key, value in subject_dict.items():
    #print(f"{key}: {value}")


# Function to split the "Grades Semester Name" into two parts
def split_semester_name(name):
    if isinstance(name, str):
        parts = name.split()
        year_name = ' '.join(parts[:2]) if len(parts) >= 2 else None  # First two words or None
        semester_name = ' '.join(parts[-2:]) if len(parts) >= 2 else None  # Last two words or None
        return year_name, semester_name
    else:
        return None, None  # Default values for non-string entries


# Applying the function to create new columns in the existing DataFrame
All_P19_apr21_Grd18_df1923['Grade Year Name'], All_P19_apr21_Grd18_df1923['Grade Semester Name'] = zip(*All_P19_apr21_Grd18_df1923['Grade Year with Semester Name'].apply(split_semester_name))


# Map the subject codes to names and create a new column 'Subject Name'
All_P19_apr21_Grd18_df1923['Grade Subject Name'] = All_P19_apr21_Grd18_df1923['Subject Code'].map(subject_dict)

# Displaying the first few rows of the final DataFrame
#print(All_P19_apr21_Grd18_df1923.head())

In [ ]:
All_P19_apr21_Grd18_df1923[All_P19_apr21_Grd18_df1923['PRN']=='1151518002556']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
9,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,10,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
10,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*025,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
11,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,5,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
12,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*015,...,2,D6,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
13,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,2,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
33849,1151518002556,10771,BHUTADA RIDDHI NISHANT,2019 Pattern,Oct-2022,08-Mar-2023,4201956,---,---,---,...,2,C7,14,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Research In Architecture II
33850,1151518002556,10771,BHUTADA RIDDHI NISHANT,2019 Pattern,Oct-2022,08-Mar-2023,4201957,---,---,---,...,2,A9,18,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
33851,1151518002556,10771,BHUTADA RIDDHI NISHANT,2019 Pattern,Oct-2022,08-Mar-2023,4201958,---,---,*022,...,3,C7,21,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Quantity Surveying & Specification Writing I
33852,1151518002556,10771,BHUTADA RIDDHI NISHANT,2019 Pattern,Oct-2022,08-Mar-2023,4201959,---,---,*016,...,3,C7,21,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Professional Practice
33853,1151518002556,10771,BHUTADA RIDDHI NISHANT,2019 Pattern,Oct-2022,08-Mar-2023,4201967J,---,---,---,...,None,None,None,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Audit Course

In [ ]:
import re
import pandas as pd

# Example usage:
line1 = 'BASIC DESIGN1201901       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex'
line2 = 'BUILDING CONSTRUCTION & MATERIALS I [P]1201902       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex'

# Define the columns for the DataFrame
columns = ['Subject Name', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3', 'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF']

def process_student_info_line(line):
    # Define the pattern to extract information
    pattern = re.compile(r'([A-Z\s&\[\]]+)(\d+)\s+(-{3}\s+){13}(\S+)\s+Ex')

    # Match the pattern in the line
    match = pattern.match(line)

    if match:
        subject_name = match.group(1).strip()
        subject_code = match.group(2)
        grades = [match.group(4)] * len(columns[2:])

        return [subject_name, subject_code] + grades
    else:
        return None

# Process each line and filter out None (lines that don't match the pattern)
data = [process_student_info_line(line1), process_student_info_line(line2)]
data = [row for row in data if row is not None]

# Create a DataFrame using the processed data
df1 = pd.DataFrame(data, columns=columns)

# Display the resulting DataFrame
#print(df1)

In [ ]:
df1

,Subject Name,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5,Tot,Tot_FFF
0,BASIC DESIGN,1201901,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---
1,BUILDING CONSTRUCTION & MATERIALS I [P],1201902,---,---,---,---,---,---,---,---,---,---,---,---,---,---,---

In [ ]:
import re
import pandas as pd

# Example usage:
lines = [
    'BASIC DESIGN1201901       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'BUILDING CONSTRUCTION & MATERIALS I [P]1201902       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'BUILDING CONSTRUCTION & MATERIALS I [SV]1201903       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'THEORY OF STRUCTURES I1201904       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'ARCHITECTURAL GRAPHICS AND DRAWING I1201905       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'HISTORY OF ARCH & CULTURE I1201906       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'COMMUNICATION SKILLS1201907       ---    ---    ---    ---    ---  * 029    ---    ---    ---    ---    ---    ---    ---  029       2   D     612',
    'WORKSHOP I1201908       ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex',
    'CRAFTS1201917A      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
    'CREATIVE WRITING1201917B      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
    'PERFORMING ARTS1201917C      ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---    ---  --- Ex%^',
]

FY_sem1_sub = ['Basic Design', 'Building Construction & Materials I[P]', 'Building Construction & Materials I[SV]',
               'Theory of Structures I', 'Architectural Graphics and Drawing I',
               'History of Arch & Culture I', 'Communication Skills', 'Workshop I', 'Audit Course', 'CRAFTS',
               'CREATIVE WRITING', 'PERFORMING ARTS']

# Define the columns for the DataFrame
columns = ['Subject Name', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3', 'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF']

def extract_subject_info(lines, subject_names):
    # Define the pattern to extract information
    pattern = re.compile(r'([A-Z\s&\[\]]+)(\d+)\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(-{3})\s+(Ex)$')

    # Process each line and filter out None (lines that don't match the pattern)
    data = [process_student_info_line(line, pattern) for line in lines if process_student_info_line(line, pattern) is not None]

    # Create a DataFrame using the processed data
    df = pd.DataFrame(data, columns=columns)

    # Filter rows based on whether any part of the line contains a substring from subject names
    df_filtered = df[df['Subject Name'].apply(lambda x: any(name in x for name in subject_names))]

    return df_filtered

def process_student_info_line(line, pattern):
    # Match the pattern in the line
    match = pattern.match(line)

    if match:
        subject_name = match.group(1).strip()
        subject_code = match.group(2)
        grades = match.groups()[2:-1]  # Extract grades for Int1 to Tot_FFF
        return [subject_name, subject_code] + list(grades)
    else:
        return None

# Extract subject information
result_df = extract_subject_info(lines, FY_sem1_sub)

# Display the resulting DataFrame
print(result_df)

Empty DataFrame
Columns: []
Index: []

#**24th & 25th Jan 2023**

##**C.G.P.A., S.G.P.A., and, Year Result all together**

In [ ]:
import pandas as pd
import re

def parse_info(cgpa_info_lines):
    info_str = ' '.join(cgpa_info_lines)

    semester_data = []
    year_data = []

    semester_info_pattern = r'(\w+ Semester) SGPA\s*:\s*([-\d.]+) Credits Earned/Total\s*:\s*(\d+/\d+)'
    total_credit_points_pattern = r'Total Credit Points:\s*(\d+)'
    year_info_pattern_with_result = r'(First|Second|Third|Fourth|Fifth) Year Result\s*:\s*(.*?)\s*Total Credits Earned\s*:\s*(\d+/\d+)'
    year_info_pattern_without_result = r'(First|Second|Third|Fourth|Fifth) Year Total Credits Earned\s*:\s*(\d+/\d+)'
    cgpa_class_pattern = r'C\.G\.P\.A\. : (\d+(\.\d+)?)\s*([\w\s]+?)(?=\d|$)'

    semester_matches = re.finditer(semester_info_pattern, info_str)
    total_credit_points_matches = re.findall(total_credit_points_pattern, info_str)
    year_matches_with_result = re.finditer(year_info_pattern_with_result, info_str)
    year_matches_without_result = re.finditer(year_info_pattern_without_result, info_str)
    cgpa_class_match = re.search(cgpa_class_pattern, info_str)

    for match in semester_matches:
        sgpa = match.group(2).strip()
        sgpa = sgpa if sgpa.replace('.', '', 1).isdigit() else None
        semester_data.append({
            'SGPA Semester Name': match.group(1),
            'Semester SGPA': sgpa,
            'Semester Credits Earned': match.group(3)
        })

    for tcp, sem_data in zip(total_credit_points_matches, semester_data):
        sem_data['Semester Total Credit Points'] = tcp

    for match in year_matches_with_result:
        year_data.append({
            'Year Result Year Name': match.group(1) + " Year",
            'Year Result': match.group(2).strip(),
            'Year Total Credits Earned': match.group(3)
        })

    for match in year_matches_without_result:
        year_data.append({
            'Year Result Year Name': match.group(1) + " Year",
            'Year Result': None,
            'Year Total Credits Earned': match.group(2)
        })

    cgpa = cgpa_class_match.group(1) if cgpa_class_match else None
    cgpa_info = {
        'C.G.P.A.': cgpa,
        'Class': cgpa_class_match.group(3).strip() if cgpa_class_match else None
    }

    return semester_data, year_data, cgpa_info

def match_year_result_to_semesters(semesters, years, cgpa_info, prn, course_year, ledger_year):
    semester_to_year_map = {
        "First Semester": "First Year",
        "Second Semester": "First Year",
        "Third Semester": "Second Year",
        "Fourth Semester": "Second Year",
        "Fifth Semester": "Third Year",
        "Sixth Semester": "Third Year",
        "Seventh Semester": "Fourth Year",
        "Eighth Semester": "Fourth Year",
        "Ninth Semester": "Fifth Year",
        "Tenth Semester": "Fifth Year",
    }

    year_result_dict = {(year_info['Year Result Year Name'], prn, course_year, ledger_year): year_info
                        for year_info in years}

    for sem in semesters:
        year_key = (semester_to_year_map.get(sem['SGPA Semester Name'], ''), prn, course_year, ledger_year)
        if year_key in year_result_dict:
            sem.update(year_result_dict[year_key])

new_data = []

# Assuming All_P19_YearDateWise_Student_Info_df1923 is the DataFrame containing the data
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    semester_info, year_info, cgpa_info = parse_info(row['Student Info Lines'])

    match_year_result_to_semesters(semester_info, year_info, cgpa_info, row['PRN'], row['Course Pattern Year'], row['Ledger Year'])

    for sem_data in semester_info:
        new_record = {
            'PRN': row['PRN'],
            'Seat No': row.get('Seat No', 'N/A'),
            'Name': row['Name'],
            'Course Pattern Year': row['Course Pattern Year'],
            'Ledger Year': row['Ledger Year'],
            'Ledger Release Date': row['Ledger Release Date'],
            **sem_data,
            **cgpa_info  # Include C.G.P.A. and Class info
        }
        new_data.append(new_record)

P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923 = pd.DataFrame(new_data)
#print(P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923.head())

###**Testing for P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923**

In [ ]:
P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned,C.G.P.A.,Class
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56,None,None
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Second Semester,0.000,28/28,0,First Year,None,56/56,None,None
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,6.571,28/28,184,Second Year,Fail A.T.K.T.,44/56,None,None
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,None,16/28,116,Second Year,Fail A.T.K.T.,44/56,None,None
4,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,First Semester,6.000,28/28,12,First Year,None,56/56,None,None
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5813,1151919002599,476,SAKSHI SANJAY JANGAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,182,NaN,NaN,NaN,None,None
5814,1151919002605,460,PULLIWAR RIJUTA PRASAD,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.536,28/28,211,NaN,NaN,NaN,None,None
5815,1151919002612,452,PATIL TEJAL RAJARAM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,26/28,212,NaN,NaN,NaN,None,None
5816,1151919002629,437,NASHRAH RAHIM,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN,None,None
5817,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,None,0/28,0,NaN,NaN,NaN,None,None

In [ ]:
#1151919001219
P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923[P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923['Ledger Year']=='Apr-2020']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned,C.G.P.A.,Class
5312,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,None,26/28,189,First Year,Fail A.T.K.T.,54/56,None,None
5313,1151919000946,393,THOMAS CELESTE HENRY,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,7.500,28/28,210,First Year,Fail A.T.K.T.,54/56,None,None
5314,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,8.714,28/28,244,First Year,None,56/56,8.500,First class with distinction
5315,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,8.286,28/28,232,First Year,None,56/56,8.500,First class with distinction
5316,1151919000960,273,GORE SHRUTI SNEHAL,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,7.929,28/28,222,First Year,None,56/56,7.982,First class with distinction
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
5643,1151919002605,346,PULLIWAR RIJUTA PRASAD,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,7.286,28/28,204,First Year,None,56/56,7.411,First class
5644,1151919002612,339,PATIL TEJAL RAJARAM,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,None,26/28,212,First Year,Fail A.T.K.T.,54/56,None,None
5645,1151919002612,339,PATIL TEJAL RAJARAM,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,7.500,28/28,210,First Year,Fail A.T.K.T.,54/56,None,None
5646,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,None,0/28,0,First Year,Fail,0/56,None,None
5647,1151919002629,324,NASHRAH RAHIM,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,None,0/28,0,First Year,Fail,0/56,None,None

In [ ]:
#1151919000953
#1151919001219
temp_apr20_0953=P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923[P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923['PRN']=='1151919000953']
temp_apr20_0953

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned,C.G.P.A.,Class
18,1151919000953,783,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,9.000,28/28,252,Second Year,None,56/56,None,None
19,1151919000953,783,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,8.679,28/28,243,Second Year,None,56/56,None,None
701,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,9.000,28/28,252,Second Year,None,56/56,None,None
702,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,8.679,28/28,243,Second Year,None,56/56,None,None
703,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,8.286,28/28,232,NaN,NaN,NaN,None,None
1587,1151919000953,11495,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2023,18-Sep-2023,Seventh Semester,8.000,28/28,224,Fourth Year,None,56/56,None,None
1588,1151919000953,11495,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2023,18-Sep-2023,Eighth Semester,8.107,28/28,227,Fourth Year,None,56/56,None,None
3185,1151919000953,11115,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,8.286,28/28,232,Third Year,None,56/56,None,None
3186,1151919000953,11115,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,8.536,28/28,239,Third Year,None,56/56,None,None
4238,1151919000953,11106,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2022,08-Mar-2023,Seventh Semester,8.000,28/28,224,NaN,NaN,NaN,None,None
5314,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,8.714,28/28,244,First Year,None,56/56,8.500,First class with distinction
5315,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,8.286,28/28,232,First Year,None,56/56,8.500,First class with distinction
5649,1151919000953,481,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,8.714,28/28,244,NaN,NaN,NaN,None,None

In [ ]:
temp_apr20_0953.iloc[:50,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned,C.G.P.A.,Class
18,1151919000953,783,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,9.000,28/28,252,Second Year,None,56/56,None,None
19,1151919000953,783,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,8.679,28/28,243,Second Year,None,56/56,None,None
701,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,9.000,28/28,252,Second Year,None,56/56,None,None
702,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,8.679,28/28,243,Second Year,None,56/56,None,None
703,1151919000953,1135,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,8.286,28/28,232,NaN,NaN,NaN,None,None
1587,1151919000953,11495,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2023,18-Sep-2023,Seventh Semester,8.000,28/28,224,Fourth Year,None,56/56,None,None
1588,1151919000953,11495,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2023,18-Sep-2023,Eighth Semester,8.107,28/28,227,Fourth Year,None,56/56,None,None
3185,1151919000953,11115,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,8.286,28/28,232,Third Year,None,56/56,None,None
3186,1151919000953,11115,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,8.536,28/28,239,Third Year,None,56/56,None,None
4238,1151919000953,11106,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2022,08-Mar-2023,Seventh Semester,8.000,28/28,224,NaN,NaN,NaN,None,None
5314,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,8.714,28/28,244,First Year,None,56/56,8.500,First class with distinction
5315,1151919000953,367,SAWANT MAITHILI VIJAY,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,8.286,28/28,232,First Year,None,56/56,8.500,First class with distinction
5649,1151919000953,481,SAWANT MAITHILI VIJAY,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,8.714,28/28,244,NaN,NaN,NaN,None,None

In [ ]:
#1151919001219
temp_apr20_1219=P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923[P19_YearDateWise_SGPA_YearResult_CGPA_Info_df1923['PRN']=='1151919001219']
temp_apr20_1219

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,SGPA Semester Name,Semester SGPA,Semester Credits Earned,Semester Total Credit Points,Year Result Year Name,Year Result,Year Total Credits Earned,C.G.P.A.,Class
72,1151919001219,639,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2021,28-Aug-2021,Third Semester,8.750,28/28,245,Second Year,None,56/56,None,None
73,1151919001219,639,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2021,28-Aug-2021,Fourth Semester,8.500,28/28,238,Second Year,None,56/56,None,None
776,1151919001219,930,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2021,09-Apr-2022,Third Semester,8.750,28/28,245,Second Year,None,56/56,None,None
777,1151919001219,930,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2021,09-Apr-2022,Fourth Semester,8.500,28/28,238,Second Year,None,56/56,None,None
778,1151919001219,930,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2021,09-Apr-2022,Fifth Semester,7.964,28/28,223,NaN,NaN,NaN,None,None
1649,1151919001219,11227,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2023,18-Sep-2023,Seventh Semester,7.750,28/28,217,Fourth Year,Fail A.T.K.T.,45/56,None,None
1650,1151919001219,11227,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2023,18-Sep-2023,Eighth Semester,None,17/28,121,Fourth Year,Fail A.T.K.T.,45/56,None,None
3237,1151919001219,10909,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2022,30-Aug-2022,Fifth Semester,7.964,28/28,223,Third Year,Fail A.T.K.T.,48/56,None,None
3238,1151919001219,10909,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2022,30-Aug-2022,Sixth Semester,None,20/28,157,Third Year,Fail A.T.K.T.,48/56,None,None
4289,1151919001219,10898,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2022,08-Mar-2023,Fifth Semester,7.964,28/28,223,Third Year,None,56/56,None,None
4290,1151919001219,10898,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2022,08-Mar-2023,Sixth Semester,7.607,28/28,213,Third Year,None,56/56,None,None
4291,1151919001219,10898,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2022,08-Mar-2023,Seventh Semester,7.750,28/28,217,NaN,NaN,NaN,None,None
5366,1151919001219,292,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2020,21-Jul-2020,First Semester,7.786,28/28,218,First Year,None,56/56,8.393,First class with distinction
5367,1151919001219,292,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Apr-2020,21-Jul-2020,Second Semester,9.000,28/28,252,First Year,None,56/56,8.393,First class with distinction
5675,1151919001219,405,KARTIKI PRAVIN DEGAMWAR,2019 Pattern,Oct-2019,25/Jan/2020,First Semester,7.786,28/28,218,NaN,NaN,NaN,None,None

#**28th 29th Jan 2024**

##**Next line credits and subject name and code separation**

both codes for this are not working

In [ ]:
import re
import pandas as pd

# Define semester subject codes
semester_subject_codes = {
    'First Year First Semester': ['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917'],
    'First Year Second Semester': ['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A'],
    'Second Year Third Semester': ['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925', '2201935','2201935F'],
    'Second Year Fourth Semester': ['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934', '2201036', '2201936O','2201936F'],
    'Third Year Fifth Semester': ['3201935', '3201936', '3201937', '3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I'],
    'Third Year Sixth Semester': ['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D'],
    'Fourth Year Seventh Semester': ['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967', '4201967J'],
    'Forth Year Eighth Semester': ['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968', '4201968K'],
    'Fifth Year Ninth Semester': ['5201967'],
    'Fifth Year Tenth Semester': ['5201968', '5201969', '5201970'],
    'Extra Subject Eleventh Semester':['9201917','22999'],
}

# Flatten the dictionary to get a list of all subject codes
all_subject_codes = [code for codes in semester_subject_codes.values() for code in codes]

# Function to get semester name based on subject code
def get_semester_name(subject_code):
    for sem, codes in semester_subject_codes.items():
        if subject_code in codes:
            return sem
    return None


def parse_student_info(student_info_lines, prn_check):
    # [Your existing code for extracting PRN, Seat No, and Name]
    prn_pattern = r'PRN:\s*(\d+)'
    seat_pattern = r'Seat no.:\s*(\d+)'
    #name_pattern = r'NAME:\s*([A-Z\s]+)'
    name_pattern = r'NAME:\s*([A-Z\s]+?)(?= Mother| Father|$)'

    prn, seat_no, name = None, None, None
    for line in student_info_lines:
        # [Your existing code for extracting PRN, Seat No, and Name]
        if 'PRN:' in line:
            prn_match = re.search(prn_pattern, line)
            seat_match = re.search(seat_pattern, line)
            name_match = re.search(name_pattern, line)
            if prn_match:
                prn = prn_match.group(1)
            if seat_match:
                seat_no = seat_match.group(1)
            if name_match:
                name = name_match.group(1).strip()
            break
    if prn != prn_check:
        return None

    grades = []
    for line in student_info_lines:
        # Check for both subject code and subject name in the line
        code_match = re.search(r'(\d{7})', line)
        name_match = re.search(r'([A-Z][A-Z\s&\[\]]+)', line)

        if code_match:
            subject_code = code_match.group(1)
        elif name_match:
            # If subject name is found, try to find corresponding subject code
            subject_name = name_match.group(1)
            subject_code = next((code for code, name in subject_dict.items() if subject_name in name), None)
        else:
            continue

        parts = line.split()
        if parts and subject_code in all_subject_codes:
            merged_grades = []
            skip_next = False
            for i, part in enumerate(parts):
                if skip_next:
                    skip_next = False
                    continue

                if part == '*':
                    if i + 1 < len(parts):
                        merged_grades.append(part + parts[i + 1])
                        skip_next = True
                    else:
                        merged_grades.append(part)
                elif merged_grades and merged_grades[-1].isalpha() and part.isdigit():
                    merged_grades[-1] += part
                elif merged_grades and part == 'FFF':
                    merged_grades[-1] += part
                else:
                    merged_grades.append(part)

            grades.append(merged_grades + [None] * (len(columns) - 6 - len(merged_grades)))

    return {
        'PRN': prn,
        'Seat No': seat_no,
        'Name': name,
        'Grades': grades
    }

# Define your columns as per the expected output
columns = ['PRN', 'Seat No', 'Name', 'Course Pattern Year', 'Ledger Year', 'Ledger Release Date', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3',
           'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining']
All_P19_YearDateWise_Grades1618_Info_df2_1923 = pd.DataFrame(columns=columns)


# Assuming YearWise_Student_Info_df24 is defined and contains the necessary data
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    # [Your existing code for iterating over the DataFrame and parsing data]
    prn_check = row['PRN']
    student_info_lines = row['Student Info Lines']
    course_pattern_year = row['Course Pattern Year']
    ledger_year = row['Ledger Year']
    ledger_release_date= row['Ledger Release Date']

    parsed_data = parse_student_info(student_info_lines, prn_check)

    if parsed_data:
        student_df = pd.DataFrame(parsed_data['Grades'], columns=columns[6:])
        student_df['PRN'] = parsed_data['PRN']
        student_df['Seat No'] = parsed_data['Seat No']
        student_df['Name'] = parsed_data['Name']
        student_df['Ledger Release Date'] = ledger_release_date
        student_df['Course Pattern Year'] = course_pattern_year
        student_df['Ledger Year'] = ledger_year


        All_P19_YearDateWise_Grades1618_Info_df2_1923 = pd.concat([All_P19_YearDateWise_Grades1618_Info_df2_1923, student_df], ignore_index=True)

# Add 'Semester Name' column
All_P19_YearDateWise_Grades1618_Info_df2_1923['Grade Year with Semester Name'] = All_P19_YearDateWise_Grades1618_Info_df2_1923['Subject Code'].apply(get_semester_name)

#Subjects and their codes
#1201901

FY_sem1_code=['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917','1201917A', '1201917B', '1201917C']
FY_sem1_sub=['Basic Design', 'Building Construction & Materials I[P]', 'Building Construction & Materials I[SV]', 'Theory of Structures I', 'Architectural Graphics and Drawing I',
                'History of Arch & Culture I', 'Communication Skills', 'Workshop I', 'Audit Course','CRAFTS','CREATIVE WRITING','PERFORMING ARTS']

FY_sem2_code=['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A']
FY_sem2_sub=['Architectural Design I', 'Building Construction & Materials II[P]', 'Building Construction & Materials II[SV]', 'Theory of Structures II', 'Architectural Graphics and Drawing II',
                'History of Arch & Culture II', 'Fundamentals of Architecture', 'Workshop II', 'Audit Course', 'Audit Course']

SY_sem3_code=['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925','2201935','2201935F']
SY_sem3_sub=['Architectural Design II', 'Building Construction & Materials III[P]', 'Building Construction & Materials III[SV]', 'Theory of Structures III', 'Computer Aided Drawing and Graphics',
                'History of Arch & Culture III', 'Building Services I[P]', 'Building Services I[SS]', 'Climatology','Audit Course','Audit Course']

SY_sem4_code=['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934','2201036']
SY_sem4_sub=['Architectural Design III', 'Building Construction & Materials IV[P]', 'Building Construction & Materials IV[SV]', 'Theory of Structures IV', 'Environmental Sciences',
                'History of Arch & Culture IV', 'Building Services II[P]', 'Building Services II[SS]', 'Site Survey and Analysis','Audit Course']

TY_sem5_code=['3201935', '3201936', '3201937','3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I']
TY_sem5_sub=['Architectural Design IV', 'Building Construction & Materials V[P]', 'Building Construction & Materials V[SV]', 'Theory of Structures V', 'Landscape Architecture',
                'Elective I[Contemporary Architecture]', 'Building Services III[P]', 'Building Services III[SS]', 'Working Drawing I','Audit Course','Audit Course','Audit Course']

TY_sem6_code=['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D']
TY_sem6_sub=['Architectural Design V[SV]', 'Architectural Design V*[P]', 'Building Construction & Materials VI', 'Theory of Structures VI', 'Research In Architecture I',
                'Elective II', 'Building Services IV[P]', 'Building Services IV[SS]', 'Working Drawing II','Audit Course','Audit Course','Audit Course','Audit Course']

FOY_sem7_code=['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967','4201967J']
FOY_sem7_sub=['Architectural Design VI', 'Advanced Building Construction & Services I', 'Urban Studies I', 'Research In Architecture II',
                'Elective III', 'Quantity Surveying & Specification Writing I', 'Professional Practice', 'Audit Course','Audit Course']

FOY_sem8_code=['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968','4201968K']
FOY_sem8_sub=['Architectural Design VII', 'Advanced Building Construction & Services II', 'Urban Studies II', 'Elective IV',
                'Elective V', 'Quantity Surveying & Specification Writing II', 'Project Management', 'Audit Course','Audit Course']

FTY_sem9_code=['5201967']
FTY_sem9_sub=['Practical Training']

FTY_sem10_code=['5201968','5201969','5201970']
FTY_sem10_sub=['Architectural Design Project','Entrepreneurship Development','Elective VI*']

Extra_sem_code=['9201917','22999']
Extra_sem_sub=['PHYSICAL EDUCATION','DEMOCRACY ELECTION AND GOVERNANCE']


# Combine the lists into a list of pairs
code_sub_pairs = [
    (FY_sem1_code, FY_sem1_sub),
    (FY_sem2_code, FY_sem2_sub),
    (SY_sem3_code, SY_sem3_sub),
    (SY_sem4_code, SY_sem4_sub),
    (TY_sem5_code, TY_sem5_sub),
    (TY_sem6_code, TY_sem6_sub),
    (FOY_sem7_code, FOY_sem7_sub),
    (FOY_sem8_code, FOY_sem8_sub),
    (FTY_sem9_code, FTY_sem9_sub),
    (FTY_sem10_code, FTY_sem10_sub),
    (Extra_sem_code, Extra_sem_sub)
    # ... [Include other semester pairs here]
]

# Create the dictionary
subject_dict = {}
for code_list, sub_list in code_sub_pairs:
    for code, sub in zip(code_list, sub_list):
        subject_dict[code] = sub

# Print the dictionary
#for key, value in subject_dict.items():
    #print(f"{key}: {value}")


# Function to split the "Grades Semester Name" into two parts
def split_semester_name(name):
    if isinstance(name, str):
        parts = name.split()
        year_name = ' '.join(parts[:2]) if len(parts) >= 2 else None  # First two words or None
        semester_name = ' '.join(parts[-2:]) if len(parts) >= 2 else None  # Last two words or None
        return year_name, semester_name
    else:
        return None, None  # Default values for non-string entries


# Applying the function to create new columns in the existing DataFrame
All_P19_YearDateWise_Grades1618_Info_df2_1923['Grade Year Name'], All_P19_YearDateWise_Grades1618_Info_df2_1923['Grade Semester Name'] = zip(*All_P19_YearDateWise_Grades1618_Info_df2_1923['Grade Year with Semester Name'].apply(split_semester_name))


# Map the subject codes to names and create a new column 'Subject Name'
All_P19_YearDateWise_Grades1618_Info_df2_1923['Grade Subject Name'] = All_P19_YearDateWise_Grades1618_Info_df2_1923['Subject Code'].map(subject_dict)

# Displaying the first few rows of the final DataFrame
#print(All_P19_YearDateWise_Grades1618_Info_df2_1923.head())

ValueError: 21 columns passed, passed data had 41 columns

In [ ]:
temp0946=All_P19_YearDateWise_Grades1618_Info_df1923[All_P19_YearDateWise_Grades1618_Info_df1923['PRN']=='1151919000960']
#1151919000960
temp0946

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
267,1151919000960,879,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2021,09-Apr-2022,2201917,---,---,---,...,10,B8,80,None,None,None,Second Year Third Semester,Second Year,Third Semester,Architectural Design II
268,1151919000960,879,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2021,09-Apr-2022,2201918,---,---,P030,...,2,O10,20,None,None,None,Second Year Third Semester,Second Year,Third Semester,Building Construction & Materials III[P]
269,1151919000960,879,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2021,09-Apr-2022,2201919,---,---,---,...,5,A9,45,None,None,None,Second Year Third Semester,Second Year,Third Semester,Building Construction & Materials III[SV]
270,1151919000960,879,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2021,09-Apr-2022,2201920,---,---,P028,...,2,B8,16,None,None,None,Second Year Third Semester,Second Year,Third Semester,Theory of Structures III
271,1151919000960,879,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2021,09-Apr-2022,2201921,---,---,---,...,2,C7,14,None,None,None,Second Year Third Semester,Second Year,Third Semester,Computer Aided Drawing and Graphics
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
46880,1151919000960,386,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*026,*037,---,...,14,None,None,None,None,None,First Year First Semester,First Year,First Semester,Theory of Structures I
46881,1151919000960,386,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,...,24,None,None,None,None,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
46882,1151919000960,386,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,...,14,None,None,None,None,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
46883,1151919000960,386,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,...,18,None,None,None,None,None,First Year First Semester,First Year,First Semester,Communication Skills
46884,1151919000960,386,GORE SHRUTI SNEHAL,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,...,16,None,None,None,None,None,First Year First Semester,First Year,First Semester,Workshop I

In [ ]:
All_P19_YearDateWise_Grades1618_Info_df1923[All_P19_YearDateWise_Grades1618_Info_df1923['Ledger Year']=='Apr-2021']

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,10,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,5,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,2,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
84,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,...,2,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,History of Arch & Culture IV
85,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*024,...,2,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[P]
86,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,...,1,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Services II[SS]
87,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,...,2,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Site Survey and Analysis
88,1151919002629,702,NASHRAH RAHIM,2019 Pattern,Apr-2021,28-Aug-2021,9201917,---,---,---,...,None,None,None,None,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

In [ ]:
All_P19_YearDateWise_Grades1618_Info_df2_1923

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,10,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,5,C7,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,...,2,F0,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,...,2,B8,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
48216,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201904,*003,*004,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Theory of Structures I
48217,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201905,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Architectural Graphics and Drawing I
48218,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201906,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,History of Arch & Culture I
48219,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201907,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Communication Skills
48220,1151919002636,459,PUJARI SAYALI DATTATRAY,2019 Pattern,Oct-2019,25/Jan/2020,1201908,---,---,---,...,0,None,None,None,None,None,First Year First Semester,First Year,First Semester,Workshop I

In [ ]:
#1151518001719
temp_apr21_1719=All_P19_YearDateWise_Grades1618_Info_df2_1923[All_P19_YearDateWise_Grades1618_Info_df2_1923['PRN']=='1151518001719']
temp_apr21_1719

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,...,Tot_FFF,Crd,Grd,GrdPnt,CrdPnt,Remaining,Grade Year with Semester Name,Grade Year Name,Grade Semester Name,Grade Subject Name
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,...,None,None,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Architectural Design III
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,048,---,---,...,None,None,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[P]
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,...,None,None,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Building Construction & Materials IV[SV]
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,028,---,---,...,0,None,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Theory of Structures IV
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,*,037,---,...,None,None,None,None,None,None,Second Year Fourth Semester,Second Year,Fourth Semester,Environmental Sciences
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
67351,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201957,*,040,---,...,None,None,None,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Elective III
67352,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201958,037,---,---,...,18,None,None,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Quantity Surveying & Specification Writing I
67353,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201959,032,---,---,...,18,None,None,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Professional Practice
67354,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,4201967J,---,---,---,...,None,None,None,None,None,None,Fourth Year Seventh Semester,Fourth Year,Seventh Semester,Audit Course
67355,1151518001719,10887,KABRA SAKSHI GOVIND,2019 Pattern,Oct-2022,08-Mar-2023,9201917,---,---,---,...,None,None,None,None,None,None,Extra Subject Eleventh Semester,Extra Subject,Eleventh Semester,PHYSICAL EDUCATION

#Orignal Grade Extraction

In [ ]:
import re
import pandas as pd


# Define semester subject codes
semester_subject_codes = {
    'First Year First Semester': ['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917'],
    'First Year Second Semester': ['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A'],
    'Second Year Third Semester': ['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925', '2201935','2201935F'],
    'Second Year Fourth Semester': ['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934', '2201036', '2201936O','2201936F'],
    'Third Year Fifth Semester': ['3201935', '3201936', '3201937', '3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I'],
    'Third Year Sixth Semester': ['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D'],
    'Fourth Year Seventh Semester': ['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967', '4201967J'],
    'Forth Year Eighth Semester': ['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968', '4201968K'],
    'Fifth Year Ninth Semester': ['5201967'],
    'Fifth Year Tenth Semester': ['5201968', '5201969', '5201970'],
    'Extra Subject Eleventh Semester':['9201917','22999'],
}

# Flatten the dictionary to get a list of all subject codes
all_subject_codes = [code for codes in semester_subject_codes.values() for code in codes]

# Function to get semester name based on subject code
def get_semester_name(subject_code):
    for sem, codes in semester_subject_codes.items():
        if subject_code in codes:
            return sem
    return None


def parse_student_info(student_info_lines, prn_check):
    # [Your existing code for extracting PRN, Seat No, and Name]
    prn_pattern = r'PRN:\s*(\d+)'
    seat_pattern = r'Seat no.:\s*(\d+)'
    #name_pattern = r'NAME:\s*([A-Z\s]+)'
    name_pattern = r'NAME:\s*([A-Z\s]+?)(?= Mother| Father|$)'


    prn, seat_no, name = None, None, None
    for line in student_info_lines:
        # [Your existing code for extracting PRN, Seat No, and Name]
        if 'PRN:' in line:
            prn_match = re.search(prn_pattern, line)
            seat_match = re.search(seat_pattern, line)
            name_match = re.search(name_pattern, line)
            if prn_match:
                prn = prn_match.group(1)
            if seat_match:
                seat_no = seat_match.group(1)
            if name_match:
                name = name_match.group(1).strip()
            break
    if prn != prn_check:
        return None

    grades = []
    for line in student_info_lines:
        parts = line.split()
        if parts and parts[0] in all_subject_codes:
            merged_grades = []
            skip_next = False
            for i, part in enumerate(parts):
                if skip_next:
                    skip_next = False
                    continue

                if part == '*':
                    if i + 1 < len(parts):
                        merged_grades.append(part + parts[i + 1])
                        skip_next = True
                    else:
                        merged_grades.append(part)
                elif merged_grades and merged_grades[-1].isalpha() and part.isdigit():
                    merged_grades[-1] += part
                elif merged_grades and part == 'FFF':
                    merged_grades[-1] += part
                else:
                    merged_grades.append(part)

            grades.append(merged_grades + [None] * (len(columns) - 6 - len(merged_grades)))

    return {
        'PRN': prn,
        'Seat No': seat_no,
        'Name': name,
        'Grades': grades
    }

# Define your columns as per the expected output
columns = ['PRN', 'Seat No', 'Name', 'Course Pattern Year', 'Ledger Year', 'Ledger Release Date', 'Subject Code', 'Int1', 'Ext1', 'Int2', 'Ext2', 'UEX', 'SS1', 'SS2', 'SS3',
           'SV1', 'SV2', 'SV3', 'SV4', 'SV5', 'Tot', 'Tot_FFF', 'Crd', 'Grd', 'GrdPnt', 'CrdPnt', 'Remaining']
All_P19_YearDateWise_Grades1618_Info_df1923 = pd.DataFrame(columns=columns)


# Assuming YearWise_Student_Info_df24 is defined and contains the necessary data
for index, row in All_P19_YearDateWise_Student_Info_df1923.iterrows():
    # [Your existing code for iterating over the DataFrame and parsing data]
    prn_check = row['PRN']
    student_info_lines = row['Student Info Lines']
    course_pattern_year = row['Course Pattern Year']
    ledger_year = row['Ledger Year']
    ledger_release_date= row['Ledger Release Date']

    parsed_data = parse_student_info(student_info_lines, prn_check)

    if parsed_data:
        student_df = pd.DataFrame(parsed_data['Grades'], columns=columns[6:])
        student_df['PRN'] = parsed_data['PRN']
        student_df['Seat No'] = parsed_data['Seat No']
        student_df['Name'] = parsed_data['Name']
        student_df['Ledger Release Date'] = ledger_release_date
        student_df['Course Pattern Year'] = course_pattern_year
        student_df['Ledger Year'] = ledger_year


        All_P19_YearDateWise_Grades1618_Info_df1923 = pd.concat([All_P19_YearDateWise_Grades1618_Info_df1923, student_df], ignore_index=True)

# Add 'Semester Name' column
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year with Semester Name'] = All_P19_YearDateWise_Grades1618_Info_df1923['Subject Code'].apply(get_semester_name)

#Subjects and their codes
#1201901

FY_sem1_code=['1201901', '1201902', '1201903', '1201904', '1201905', '1201906', '1201907', '1201908', '1201917','1201917A', '1201917B', '1201917C']
FY_sem1_sub=['Basic Design', 'Building Construction & Materials I[P]', 'Building Construction & Materials I[SV]', 'Theory of Structures I', 'Architectural Graphics and Drawing I',
                'History of Arch & Culture I', 'Communication Skills', 'Workshop I', 'Audit Course','CRAFTS','CREATIVE WRITING','PERFORMING ARTS']

FY_sem2_code=['1201909', '1201910', '1201911', '1201912', '1201913', '1201914', '1201915', '1201916', '1201918','1201918A']
FY_sem2_sub=['Architectural Design I', 'Building Construction & Materials II[P]', 'Building Construction & Materials II[SV]', 'Theory of Structures II', 'Architectural Graphics and Drawing II',
                'History of Arch & Culture II', 'Fundamentals of Architecture', 'Workshop II', 'Audit Course', 'Audit Course']

SY_sem3_code=['2201917', '2201918', '2201919', '2201920', '2201921', '2201922', '2201923', '2201924', '2201925','2201935','2201935F']
SY_sem3_sub=['Architectural Design II', 'Building Construction & Materials III[P]', 'Building Construction & Materials III[SV]', 'Theory of Structures III', 'Computer Aided Drawing and Graphics',
                'History of Arch & Culture III', 'Building Services I[P]', 'Building Services I[SS]', 'Climatology','Audit Course','Audit Course']

SY_sem4_code=['2201926', '2201927', '2201928', '2201929', '2201930', '2201931', '2201932', '2201933', '2201934','2201036']
SY_sem4_sub=['Architectural Design III', 'Building Construction & Materials IV[P]', 'Building Construction & Materials IV[SV]', 'Theory of Structures IV', 'Environmental Sciences',
                'History of Arch & Culture IV', 'Building Services II[P]', 'Building Services II[SS]', 'Site Survey and Analysis','Audit Course']

TY_sem5_code=['3201935', '3201936', '3201937','3201938', '3201939', '3201940', '3201941', '3201942', '3201943', '3201953','3201953G','3201953I']
TY_sem5_sub=['Architectural Design IV', 'Building Construction & Materials V[P]', 'Building Construction & Materials V[SV]', 'Theory of Structures V', 'Landscape Architecture',
                'Elective I[Contemporary Architecture]', 'Building Services III[P]', 'Building Services III[SS]', 'Working Drawing I','Audit Course','Audit Course','Audit Course']

TY_sem6_code=['3201944', '3201945', '3201946', '3201947', '3201948', '3201949', '3201950', '3201951', '3201952', '3201954','3201954G','3201954I','3201954D']
TY_sem6_sub=['Architectural Design V[SV]', 'Architectural Design V*[P]', 'Building Construction & Materials VI', 'Theory of Structures VI', 'Research In Architecture I',
                'Elective II', 'Building Services IV[P]', 'Building Services IV[SS]', 'Working Drawing II','Audit Course','Audit Course','Audit Course','Audit Course']

FOY_sem7_code=['4201953', '4201954', '4201955', '4201956', '4201957', '4201958', '4201959', '4201967','4201967J']
FOY_sem7_sub=['Architectural Design VI', 'Advanced Building Construction & Services I', 'Urban Studies I', 'Research In Architecture II',
                'Elective III', 'Quantity Surveying & Specification Writing I', 'Professional Practice', 'Audit Course','Audit Course']

FOY_sem8_code=['4201960', '4201961', '4201962', '4201963', '4201964', '4201965', '4201966', '4201968','4201968K']
FOY_sem8_sub=['Architectural Design VII', 'Advanced Building Construction & Services II', 'Urban Studies II', 'Elective IV',
                'Elective V', 'Quantity Surveying & Specification Writing II', 'Project Management', 'Audit Course','Audit Course']

FTY_sem9_code=['5201967']
FTY_sem9_sub=['Practical Training']

FTY_sem10_code=['5201968','5201969','5201970']
FTY_sem10_sub=['Architectural Design Project','Entrepreneurship Development','Elective VI*']

Extra_sem_code=['9201917','22999']
Extra_sem_sub=['PHYSICAL EDUCATION','DEMOCRACY ELECTION AND GOVERNANCE']


# Combine the lists into a list of pairs
code_sub_pairs = [
    (FY_sem1_code, FY_sem1_sub),
    (FY_sem2_code, FY_sem2_sub),
    (SY_sem3_code, SY_sem3_sub),
    (SY_sem4_code, SY_sem4_sub),
    (TY_sem5_code, TY_sem5_sub),
    (TY_sem6_code, TY_sem6_sub),
    (FOY_sem7_code, FOY_sem7_sub),
    (FOY_sem8_code, FOY_sem8_sub),
    (FTY_sem9_code, FTY_sem9_sub),
    (FTY_sem10_code, FTY_sem10_sub),
    (Extra_sem_code, Extra_sem_sub)
    # ... [Include other semester pairs here]
]

# Create the dictionary
subject_dict = {}
for code_list, sub_list in code_sub_pairs:
    for code, sub in zip(code_list, sub_list):
        subject_dict[code] = sub

# Print the dictionary
#for key, value in subject_dict.items():
    #print(f"{key}: {value}")


# Function to split the "Grades Semester Name" into two parts
def split_semester_name(name):
    if isinstance(name, str):
        parts = name.split()
        year_name = ' '.join(parts[:2]) if len(parts) >= 2 else None  # First two words or None
        semester_name = ' '.join(parts[-2:]) if len(parts) >= 2 else None  # Last two words or None
        return year_name, semester_name
    else:
        return None, None  # Default values for non-string entries

# Applying the function to create new columns in the existing DataFrame
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year Name'], All_P19_YearDateWise_Grades1618_Info_df1923['Grade Semester Name'] = zip(*All_P19_YearDateWise_Grades1618_Info_df1923['Grade Year with Semester Name'].apply(split_semester_name))


# Map the subject codes to names and create a new column 'Subject Name'
All_P19_YearDateWise_Grades1618_Info_df1923['Grade Subject Name'] = All_P19_YearDateWise_Grades1618_Info_df1923['Subject Code'].map(subject_dict)

# Displaying the first few rows of the final DataFrame
#print(All_P19_YearDateWise_Grades1618_Info_df1923.head())

In [ ]:
All_P19_apr21_Grd18_df1923.iloc[:20,:20]

,PRN,Seat No,Name,Course Pattern Year,Ledger Year,Ledger Release Date,Subject Code,Int1,Ext1,Int2,Ext2,UEX,SS1,SS2,SS3,SV1,SV2,SV3,SV4,SV5
0,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,PRN:,1151518001719,Seat,no.:,631,NAME:,KABRA,SAKSHI,GOVIND,Mother,-,RADHA,None,None
1,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,---,---,---,---,---,---,---,*115,---,---
2,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*024,*048,---,---,---,---,---,---,---,---,---
3,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,---,---,---,---,---,*067,---,---,---,---
4,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*016,*028,---,---,---,---,---,---,---,---,---
5,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,---,---,*037,---,---,---,---,---,---,---
6,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,---,---,*025,---,---,---,---,---,---,---
7,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*025,*059,---,---,---,---,---,---,---,---,---
8,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,---,---,*034,---,---,---,---,---,---,---
9,1151518001719,631,KABRA SAKSHI GOVIND,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,---,---,*027,---,---,---,---,---,---,---
10,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,PRN:,1151518002556,Seat,no.:,556,NAME:,BHUTADA,RIDDHI,NISHANT,Mother,-,SARITA,NISHANT,BHUTADA
11,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201926,---,---,---,---,---,---,---,---,---,---,*108,---,---
12,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201927,---,---,*025,*052,---,---,---,---,---,---,---,---,---
13,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201928,---,---,---,---,---,---,---,---,*035,---,---,---,---
14,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201929,---,---,*015,*035,---,---,---,---,---,---,---,---,---
15,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201930,---,---,---,---,---,*031,---,---,---,---,---,---,---
16,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201931,---,---,---,---,---,*026,---,---,---,---,---,---,---
17,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201932,---,---,*021,*049,---,---,---,---,---,---,---,---,---
18,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201933,---,---,---,---,---,*035,---,---,---,---,---,---,---
19,1151518002556,556,BHUTADA RIDDHI NISHANT,2019 Pattern,Apr-2021,28-Aug-2021,2201934,---,---,---,---,---,*026,---,---,---,---,---,---,---